//! Litestream sidecar management for Headscale HA (R040-F21).
//!
//! On Phase 2 leader election:
//! 1. Enable + start `litestream-replicate.service` so WAL frames are
//!    continuously streamed to S3 while this node is the leader.
//!
//! On leadership loss:
//! 1. Stop `litestream-replicate.service` so only the leader replicates.
//!    (Followers pre-warm by periodic snapshot pulls — not implemented here
//!    yet; relevant only when promotion latency matters at >100 nodes.)
//!
//! ## The restore leg moved (R858-F17)
//!
//! This module used to also run `litestream restore` before starting
//! Headscale. That leg is gone: the headscale `WorkloadSpec` now declares a
//! `yah.durability.*` tier (`crate::headscale_appliance::appliance_spec`), so
//! kamaji's hydrate-on-place fills `headscale.db` from turso-backup's own
//! object-store prefix before the appliance ever starts — see that function's
//! doc comment for why the prefix differs from this module's. The replicate
//! leg below is untouched and keeps writing to litestream's own prefix; both
//! are readers of the live DB file now (turso-backup's source opens are
//! read-only), so the two coexist. Retiring replication too is a separate,
//! live-cluster-gated act — nothing here proves a turso-backup tail against
//! the live coordination server yet.
//!
//! ## Credentials
//!
//! Litestream reads S3 credentials from environment variables:
//!   `LITESTREAM_ACCESS_KEY_ID` / `LITESTREAM_SECRET_ACCESS_KEY`
//! These must be present in the systemd unit's environment (via
//! `EnvironmentFile=/etc/yah-cloud/litestream.env` or a direct
//! `Environment=` directive).  The yubaba does not manage the credentials
//! themselves; inject them at provision time via cloud-init.
//!
//! ## S3 URL format
//!
//! `s3://bucket/prefix?endpoint=https://fsn1.your-objectstorage.com`
//!
//! The `?endpoint=` query parameter is passed through to litestream's
//! `endpoint` config key (Hetzner Object Storage, Backblaze B2, MinIO, etc.).
//!
//! @yah:ticket(R591-T3, "Turn on litestream DB continuity end-to-end (--litestream-s3-url + restore-on-place)")
//! @yah:status(review)
//! @yah:at(2026-08-12T21:52:38Z)
//! @yah:assignee(agent:bundle-anthropic-ashguard)
//! @yah:parent(R591)
//! @yah:next("Set --litestream-s3-url so leader.rs::on_became_leader's litestream restore + replicate sidecar actually run; verify a freshly-placed node restores headscale.db from S3 before it starts serving. Async replication = small RPO (a few writes) on failover — acceptable for headscale's low, mostly-static write rate.")
//! @yah:handoff("THE PATH WAS NOT MERELY UNCONFIGURED - IT WAS BROKEN IN THREE PLACES, and setting --litestream-s3-url alone would have replicated nothing. All three are fixed. (1) litestream::install() was DEAD CODE: grep across oss/yubaba + app/ found callers for restore/start/stop and none for install, so /etc/yah-cloud/litestream.yml was never written on any node. Both consumers name that path, so every restore failed at 'no such file' into a warn! and every systemctl start ran against a unit that had never been written, into a discarded exit status. leader.rs::on_became_leader now calls install() before restore. (2) generate_config emitted MALFORMED YAML. (3) The sidecar unit was bound to a systemd unit R591-F1 retires.")
//! @yah:handoff("DEFECT 2, THE MALFORMED YAML, and it was invisible by construction. generate_config built the file with one format! whose `\\` line-continuation stripped the leading whitespace of the continued line, so access-key-id landed at COLUMN 0 instead of 8 - a top-level key, not a sibling of `- url:`, leaving the replica with no credentials at all. The pre-existing test passed straight through it because it only asked whether the string LITESTREAM_ACCESS_KEY_ID appeared somewhere in the output. Rebuilt as explicit pushes against a named REPLICA_KEY_INDENT constant. FALSIFIED, NOT ASSUMED: I restored the old format string behind a probe and re-ran - every_replica_key_is_indented_under_its_url FAILS with `left: 0, right: 8`, the exact bug, and passes with the fix. Probe removed; grep FALSIFICATION PROBE in litestream.rs returns nothing.")
//! @yah:handoff("DEFECT 3 IS AN F1 INTERACTION, so it had to be caught in this pass rather than filed. The sidecar unit carried BindsTo=headscale.service and WantedBy=headscale.service. R591-F1 re-homes headscale onto kamaji and DISABLES that systemd unit, so on a re-homed node BindsTo would have stopped replication the instant it started, and the [Install] target orders against a unit that never runs. The unit now has no reference to headscale.service and no [Install] section at all - it is never enabled, only started and stopped by leader.rs, which is the actual lifecycle owner. Restart is also on-failure -> always, the same lesson as the appliance: a replicate process that exits 0 has stopped replicating.")
//! @yah:gotcha("THE DB IS NOT THE WHOLE OF CONTINUITY, and litestream structurally cannot carry the rest. noise_private.key (72 bytes, /var/lib/yah-cloud/headscale/) is the appliance's IDENTITY, not its data: move the appliance without it and EVERY node's stored server identity mismatches at once - a worse outage than the one this relay is fixing, because it is silent and fleet-wide. The mechanism is R600/W273's raft-replicated cluster secret store (SecretRef::Cluster + SecretMount Cluster->File), the same one standing up for TLS certs. Do NOT invent a second secret path for it. Recorded in headscale_appliance.rs's module docs under 'What is NOT here' so the next reader of the spec meets it there.")
//! @yah:next("THE ACME-CACHE BULLET, CORRECTED: it said 'with TLS moved to the CF edge (R591-T2)'. T2's premise was reframed on 2026-08-12 - TLS now terminates at the fleet's own passway front doors, not a rented edge. The CONCLUSION is unchanged and still the reason this matters: once headscale stops terminating its own Let's Encrypt, the acme-cache is no longer state that has to survive a failover, which removes the one piece litestream does not carry. Only the mechanism changed.")
//! @yah:next("I DID NOT SET --litestream-s3-url, and deliberately did not invent a value. There is NO litestream bucket declared anywhere in the tree - grep over .yah/infra/ and .yah/docs/guides/ returns nothing - so the URL, the provider and the credentials are all an operator decision, not a default I could defend. Everything downstream of that decision is now built and tested. To turn it on: (1) create the bucket and note its s3://bucket/prefix?endpoint=... URL; (2) write LITESTREAM_ACCESS_KEY_ID / LITESTREAM_SECRET_ACCESS_KEY into /etc/yah-cloud/litestream.env on each candidate node (the sidecar unit already reads it via EnvironmentFile=-); (3) add --litestream-s3-url <URL> to yubaba.service's ExecStart (app/yah/cli/resources/yubaba.service:47) and roll it. On the next leadership transition install() writes the config + unit, restore runs, and the sidecar starts.")
//! @yah:next("THE VERIFICATION THIS TICKET ASKS FOR ('a freshly-placed node restores headscale.db from S3 before it starts serving') IS NOW ORDERED CORRECTLY IN CODE - install -> restore -> start the appliance -> start the sidecar, in on_became_leader - but has NOT been exercised against a real bucket. Do that on the dev cluster (us-west-011/013/014), which is the sanctioned testbed, not on prod.")
//! @yah:verify("cargo test -p yubaba --lib = 435 passed / 0 failed (was 417 at the start of this relay). 5 new litestream tests: every_replica_key_is_indented_under_its_url (the falsified one, both with and without an endpoint), the_endpoint_query_becomes_a_key_and_leaves_the_url, the_sidecar_is_not_bound_to_the_retired_headscale_unit, the_sidecar_restarts_on_a_graceful_exit, the_unit_and_the_restore_share_one_config_path.")
//! @yah:verify("cargo check -p yubaba clean; cargo clippy -p yubaba --lib reports zero warnings on litestream.rs, leader.rs or headscale_appliance.rs (10 crate-wide warnings, all pre-existing and on untouched files - same count as before this relay).")
//! @yah:verify("The unit text is now generated by one function used by BOTH install() and the tests, so a directive can no longer be asserted in a copy that has drifted from what is written to /etc/systemd/system.")
//! @yah:gotcha("SUPERSEDED IN PART BY R858 (2026-09-04) — two claims in this ticket's own annotations are now false, and a reader will go looking for code that is gone. (1) LITESTREAM_CONFIG_PATH is no longer /etc/yah-cloud/litestream.yml; it is /var/lib/yah/yubaba/litestream.yml. The /etc path could never work: yubaba.service sets ProtectSystem=strict and grants no path under /etc, so install()'s write was EROFS on every fleet node and leader.rs absorbed the Err into a warn!. That was a FOURTH defect on this path, and it defeated this ticket's three fixes. (2) The verify line \"the unit text is now generated by one function used by BOTH install() and the tests\" no longer holds — unit_text() is DELETED. The unit is static, yubaba was never permitted to write it, so it now ships in the release tarball as app/yah/cli/resources/litestream-headscale.service and its directive assertions live in app/yah/cli/tests/camp_systemd_unit_emit.rs. This ticket's remaining next (\"exercise against a real bucket\") is now R858-T5; the bucket it lacked exists.")
//!
//! @yah:ticket(R858-T5, "Prove litestream restore-before-serve against the real bucket on the dev cluster")
//! @yah:status(review)
//! @yah:at(2026-09-08T19:14:55Z)
//! @yah:assignee(agent:bundle-anthropic-ashguard)
//! @yah:parent(R858)
//! @yah:next("Tier: Cleric — the code path is built and unit-tested; this is the live exercise it has never had.")
//! @yah:gotcha("R591-T3 asked for exactly this and could not do it (no bucket existed). The bucket now exists and everything downstream is built, so this is the ticket that turns \"ordered correctly in code\" into \"observed working\". ON THE DEV CLUSTER (us-west-011/013/014), NOT PROD — R591-T2 and T3 both say so, and us-west-011 was online 2026-09-04.")
//! @yah:next("RUNBOOK. (1) On each dev node write /etc/yah-cloud/litestream.env with YUBABA_LITESTREAM_S3_URL=s3://yah-headscale/dev?endpoint=https://3948dc292e724e71b0deefde0ea95999.r2.cloudflarestorage.com plus LITESTREAM_ACCESS_KEY_ID / LITESTREAM_SECRET_ACCESS_KEY from vault slots cloudflare-r2-access-key-id / cloudflare-r2-secret-key. USE A `dev` PREFIX, NOT `headscale` — do not let a dev cluster's replica land on the prefix prod will restore from. (2) Roll a yubaba carrying this session's changes (the unit and the litestream binary now arrive via cloud-init/tarball, so an existing node needs scripts/roll-node.sh, not just a restart). (3) Force a leadership transition and watch on_became_leader's ordering: install -> restore -> deploy appliance -> start sidecar. (4) The assertion that matters is RESTORE-BEFORE-SERVE, so seed a row into the dev headscale DB, let it replicate, transfer leadership, and confirm the row is present on the NEW node BEFORE it answers — not merely that the file exists.")
//! @yah:gotcha("`litestream restore` is called with -if-replica-exists, so it is a NO-OP when the prefix is empty and returns success. A first run therefore proves nothing about restore; it only proves the config parsed. Seed the replica first or the test passes vacuously — which is the same trap R591-T3's malformed-YAML bug hid behind.")
//! @yah:handoff("PROVEN LIVE, NON-VACUOUSLY, ON THE DEV RAFT GROUP — and the leg had never worked, for a FIFTH reason nobody had found. R591-T3 found three defects on this path, R858 found a fourth (the /etc EROFS write). This is the fifth and it made the RESTORE half inert even after the other four were fixed: litestream::restore passed `-config <cfg>` AND the replica URL as the positional, and litestream 0.3.13 refuses that combination outright — `ERROR failed to run error=\"cannot specify a replica URL and the -config flag\"`, exit 1, absorbed by leader::on_became_leader into a warn!. Every restore on every node, every time, since the function was written. FIXED: the positional is now the DB PATH the config maps (litestream's two forms are mutually exclusive — `-config` + a dbs[].path, or a replica URL alone). Extracted as the pure `litestream::restore_args` so the shape is assertable without a litestream binary, with three tests; the one that matters asserts no argument may be an s3:// URL while -config is passed.")
//! @yah:verify("cargo test -p yubaba --lib = 798 passed / 0 failed (was 793 before this session's tests; +3 mine, +2 from a peer's concurrent edit). cargo clippy -p yubaba --lib reports nothing on litestream.rs or leader.rs. NOT CLAIMED: nothing committed, no prod node touched, no coordinator moved, and the CALL-SITE ordering is pinned only by the live journal above — no unit test drives a real reconcile tick, so a future edit could move the hydration back behind the probe without failing the suite.")
//! @yah:gotcha("THREE THINGS THE LIVE RUN SHOWED THAT BELONG TO OTHER TICKETS, recorded here because they were measured in the same journal. (1) R858-T7's dead-owner fencing DOES NOT FIRE when the surviving leader has no lease history for the dead owner — us-west-013 won the election after 011 was stopped and never took the appliance, because 011 is absent from the node-lease channel entirely while present on raft-heartbeat as state \"unknown\", and owner_lease_expired reads None as \"no evidence\". Full measurement on R858-T7; that ticket is at review and must not be signed off as-is. (2) The redundant SetIngressOwner from a non-leader still logs `ERROR failed to set ingress owner in raft: has to forward request to: Some(13)` — the narrow defect @Ashguard:golem described on R858-T3, still present and still an ERROR. (3) R858-T2's identity guard fired correctly and loudly on both shapes: with no key on disk `headscale is about to MINT A FRESH IDENTITY that no existing node will accept`, and with a key present but no cluster store `THE APPLIANCE IS NOT PORTABLE`. Its remedy line is exact and worth keeping. NOTE the dev group has no cluster KEK (/var/lib/yah/yubaba/cluster.kek absent), so the dev headscale minted its own identity — the dev tailnet is NOT the prod one and nothing about it should be read as evidence about prod's noise key.")
//! @yah:cleanup("litestream restore leaves headscale.db.tmp-shm and headscale.db.tmp-wal beside the restored DB (observed on us-west-011 after a successful restore). Harmless litter, removed by hand this pass; nothing in leader.rs or litestream.rs cleans them up.")
//!
//! @yah:ticket(R858-S6, "Can turso-backup replace litestream as the headscale DB replicator?")
//! @yah:status(review)
//! @yah:at(2026-09-06T09:31:39Z)
//! @yah:kind(spike)
//! @yah:assignee(agent:bundle-anthropic-ashguard)
//! @yah:parent(R858)
//! @yah:next("Tier: Cleric — one focused compatibility question with a clear yes/no, and a real payoff either way.")
//! @yah:gotcha("THE PREMISE THAT MAKES THIS WORTH ASKING: turso-backup and litestream do the SAME JOB. Both tail a sqlite WAL to S3-compatible storage and restore by replay. turso-backup additionally carries two-level fencing (R732-F2), an RPO watermark (R574-T4), bounded spill backpressure, one-puller-per-box fan-out, and frame batching (R761-F2) — none of which litestream has. It is ours, in-tree, and versioned with everything else. R858 pinned litestream to 0.3.13 with hand-computed checksums and an arch switch in cloud-init BECAUSE 0.5.x is the incompatible LTX rewrite; adopting turso-backup deletes that pin, the third-party download, and the version-migration problem in one move. NOTE oss/turso-backup is a SUBCAMP (its own .yah/camp.toml) so it is outside this board's scan set — this annotation is deliberately homed on the yubaba side, in the module the swap would replace.")
//! @yah:gotcha("THE CORE COMPATIBILITY QUESTION IS ANSWERED: YES. Probed 2026-09-04 by @Ashguard:dragon. turso_core CAN read a WAL written by upstream C SQLite — i.e. by a foreign process such as headscale's Go driver. METHOD, so it can be rebuilt as a proper test: create a WAL-mode db with the SYSTEM sqlite3 binary (3.32.2, upstream C — the writer must NOT be turso or the probe is circular); write two more rows from a second sqlite3 process and KILL -9 it mid-session so the frames stay uncheckpointed (sqlite CHECKPOINTS ON CLEAN CLOSE — my first attempt left a 0-byte WAL and was vacuous, which is the trap here); then call `turso_backup::stream::raw_consistent_copy_live(path, 4096)`. RESULT: Ok, 12288 bytes, header \"SQLite format 3\\0\", and reading the restored image back with upstream sqlite3 returned 5 rows — including the 2 that existed ONLY in the foreign-written WAL. So the frames were genuinely parsed and replayed across engines, not skipped.")
//! @yah:next("SPLIT THE TICKET IN TWO — HYDRATION AND REPLICATION ARE INDEPENDENT, AND ONLY ONE OF THEM IS HARD. (1) HYDRATION (cold start / catastrophic loss) NEEDS NO FOREIGN-PROCESS INTERACTION AT ALL: restore = fetch base snapshot + replay frames -> write a plain sqlite file at headscale's `database.sqlite.path` -> THEN start headscale. turso-backup already emits exactly that artifact — its own docs say \"a self-contained vanilla-SQLite image (page-offset stable, no -wal sidecar required)\", and the probe above confirmed upstream sqlite reads it. headscale opens a file that is already correct and never learns R2 exists. This is W338's Job-archetype restore step, `local` + `self`, and it is safe to build FIRST and independently. (2) REPLICATION (steady state) is the leg that reads a live foreign WAL; the format question is now answered, so what remains is operational — checkpoint races, and whether headscale's own autocheckpoint can fold frames out from under a tail between calls.")
//! @yah:gotcha("MOST OF THIS WAS ALREADY BUILT — R005-F4 (status: review, annotated in oss/turso-backup/src/stream.rs) is exactly \"Concurrent-writer-safe raw copy: read-only main + WAL-frame replay (no TRUNCATE-checkpoint dependency), for backing up under a live writer\". Its `raw_consistent_copy_live` opens a turso_core connection with `wal_auto_actions_disable()` so it cannot fold the WAL, reads the main file, walks frames 1..=max_frame, applies up to the last commit frame and drops the uncommitted tail. Its doc already states the foreign-writer premise: \"a concurrent writer in a separate connection only ever extends the WAL (the main file is only written by a checkpoint)\". And `tail_frames` is generic over `WalSeam` and only READS — it does not require writes to flow through turso. So the architecture was foreign-writer-shaped all along; the only untested leg was the cross-engine WAL FORMAT, and that is the leg just proved.")
//! @yah:assumes("REMAINING UNKNOWN, narrowed from the original: not the format, but the CHECKPOINT RACE. `tail_frames` resumes from a watermark of (checkpoint_seq, max_frame); headscale runs its own connection with its own autocheckpoint policy, so it can fold WAL frames into the main file between two tail calls. stream.rs already handles a checkpoint_seq advance by treating it as a restart and re-uploading 1..=max_frame, so the mechanism exists — but it has never been exercised against a writer whose checkpoints we neither trigger nor observe. Measure the actual fold rate on headscale's live db before assuming the restart path is cheap: the WAL was 8.4 MB on 2026-09-04 against a 94 KB main file, which suggests headscale is NOT checkpointing aggressively and the restart path may be rare.")
//! @yah:handoff("WHAT DID NOT HAPPEN, stated plainly because the above reads like a lot: NO live box was touched, no ssh, no network beyond cargo's registry. No production code changed — the only edits are a new example file and its [[example]] stanza in oss/turso-backup/Cargo.toml. litestream is untouched and remains the replicator; R858's 0.3.13 pin and its hand-computed checksums stay exactly as they are, and this spike does NOT authorise deleting them. leader.rs was not opened (held by @Ashguard:golem and @Ashguard:coffee). Nothing was committed.")
//! @yah:verify("REPRODUCE ANY CLAIM: `cd oss/turso-backup && cargo run --example foreign_checkpoint_probe` runs all probes; pass letters to select (a = process-restart regime, b = fold then shorter WAL, f = fold then longer WAL, c = hydration, d = liveness under a held seam, g = mutual exclusion + lock bypass, e = default autocheckpoint fold rate). `PROBE_SQLITE3=/path/to/sqlite3` swaps the foreign writer; the run prints the version it used and a non-upstream binary invalidates the whole run. Probe D is watchdogged — the first version of it hung for ten minutes, which was itself the first sign of Finding 1.")
//! @yah:handoff("VERDICT — can turso-backup replace litestream as the headscale DB replicator? **YES FOR HYDRATION, NO FOR REPLICATION, TODAY.** The ticket's instruction to split was right, and the measurement is emphatic about which half is hard. HYDRATION (cold start / failover restore) is a clean yes: it needs no foreign-process interaction, and turso-backup already emits the exact artifact headscale wants. REPLICATION (steady-state WAL tailing of a live headscale) is a no as the code stands — not because of the WAL format, which is fine, but because of two independently disqualifying defects measured below. Filed as R858-F17 (hydration, go), R858-B18 (the coexistence lock), R858-B19 (the restart-detection bug).")
//! @yah:handoff("HOW IT WAS MEASURED, so the next agent can distrust me cheaply. New harness: oss/turso-backup/examples/foreign_checkpoint_probe.rs (+ its [[example]] stanza in that crate's Cargo.toml). Seven probes, A/B/C/D/E/F/G. Every writer is the SYSTEM sqlite3 binary (3.51.0 at /usr/bin/sqlite3, upstream C) — never turso, or the probe is circular. Two traps are handled explicitly and both bit me first: (1) sqlite CHECKPOINTS ON CLEAN CLOSE, so every writer that must leave frames behind is SIGKILLed after a sentinel SELECT proves its statements ran; (2) READING a live source with sqlite3 also folds its WAL on close — my first pass did exactly that and silently destroyed the condition under test midway through probe B, so live sources are now read via rows_via_copy(), which snapshots the db/-wal/-shm trio first. The harness also parses the 32-byte WAL header off disk (wal_hdr) so that engine-independent ground truth sits next to whatever turso reports.")
//! @yah:handoff("FINDING 1 (MEASURED, probes G and D) — turso-backup CANNOT OPEN A DATABASE headscale IS HOLDING. This is prior to the checkpoint race the ticket asked about and it subsumes it. turso_core 0.7.2 takes a WHOLE-FILE EXCLUSIVE fcntl lock at open (io/unix.rs:70, lock_file(true)), so with a foreign sqlite3 connection merely OPEN AND IDLE on the file, CoreWalSeam::open and raw_consistent_copy_live both fail outright: 'Locking error: Failed locking file ... File is locked by another process'. It is symmetric: with the seam held first, the foreign writer is refused with 'database is locked (5)' — the identical write took 4.3ms in the no-seam control — and a foreign PRAGMA wal_checkpoint(TRUNCATE) gives up with the same error after honouring its 2s busy_timeout. A seam held across foreign activity also never sees it (probe D4). headscale holds one connection for its entire process lifetime, so tail_frames cannot run against a live headscale at all. IT IS A GUARD, NOT A FORMAT PROBLEM: with LIMBO_DISABLE_FILE_LOCK=1 (turso_core io/common.rs) the same copy succeeds, integrity_check ok, and includes a row the foreign holder wrote after we had already been refused once. But that flag is process-wide and buys no shared locking protocol — turso locks the whole file, C SQLite uses byte-range locks plus the -shm WAL index, neither observes the other — so it converts 'refuses to open' into 'may read torn state'. Tracked as R858-B18.")
//! @yah:handoff("FINDING 2 (MEASURED, probes A/B/F, cross-checked by E) — THE CHECKPOINT RACE IS REAL AND IT FAILS SILENTLY, and the ticket's premise that the restart path merely 'has never been exercised' was too generous: it does not fire at all in the case that matters. There are TWO foreign-checkpoint regimes and tail_frames is only correct in one. (a) IN-PROCESS AUTOCHECKPOINT — a long-lived writer folding its own WAL at the default 1000-page threshold reuses the WAL file and DOES increment checkpoint_seq monotonically (measured 0 -> 8, salt1 d492ed8a -> d492ed92 in lockstep). Restart detection would work here. (b) WRITER PROCESS RESTART — when the LAST connection closes, SQLite checkpoints and DELETES the WAL, and the next writer creates a fresh WAL back at checkpoint_seq 0 with brand-new random salt (measured b83c03f5 -> 9ca89e39, unrelated). checkpoint_seq goes 0 -> 0 across a completely different WAL, the Restarted branch never fires, and the sink splices two WAL generations into one chain. CONSEQUENCES, both with restore_latest_stream REPORTING SUCCESS and no error raised anywhere: probe B (new WAL shorter than the watermark) -> tail returns Empty forever, restore yields a 9-row image against a 12-row source that passes PRAGMA integrity_check — a plausible, silently stale database. Probe F (new WAL longer, with an early post-fold write whose pages nothing later rewrites) -> restore reports frames_replayed 57 / generations 2 and produces a file that upstream sqlite3 rejects with 'database disk image is malformed (11)'. Regime (b) is NOT exotic for this fleet — R858 exists because headscale gets torn down and redeployed on leadership change. Tracked as R858-B19, with the fix the data points at: carry the WAL salt in the watermark, since it moves in BOTH regimes while checkpoint_seq moves in only one.")
//! @yah:handoff("FINDING 3 (MEASURED, probe C) — HYDRATION WORKS, and it is the half worth taking now. A WAL written by upstream C sqlite 3.51.0 and left uncheckpointed (writer SIGKILLed mid-session) copies through raw_consistent_copy_live to an 8192-byte image that upstream sqlite3 reads with PRAGMA integrity_check = ok and the exact live row count, with no -wal sidecar required. The source was verified UNPERTURBED by the copy — identical WAL salt and max_frame before and after — which matters because the copy is the thing that would run against a real headscale database. This independently reconfirms @Ashguard:dragon's 2026-09-04 cross-engine format result on a different sqlite (3.51.0 vs their 3.32.2). And hydration dodges Finding 1 by construction: it runs BEFORE headscale starts, when nothing else holds the file, so the exclusive lock is a non-issue.")
//! @yah:handoff("COST — WHICH HALF IS MEASURED AND WHICH IS INFERRED, since the ticket asked for exactly this. MEASURED, locally (probe E): with sqlite's DEFAULT wal_autocheckpoint (confirmed 1000 pages) and a long-lived writer doing 200-byte single-row transactions into an indexed table, the WAL folded 8 times in 3000 transactions — ONE RESTART PER ~375 WRITES. That is frequent, not rare. INFERRED, not measured: how often the LIVE headscale folds. I could not reach the box and did not try. The ticket's prior — an 8.4 MB WAL against a 94 KB main file on 2026-09-04 — is consistent with headscale folding much LESS often than my local writer (8.4 MB is ~2050 pages, twice the 1000-page default threshold), which would point at either a non-default autocheckpoint or a long-lived reader blocking backfill; I could not distinguish those from here. ALSO INFERRED: yubaba's emitted headscale config (oss/yubaba/crates/cloud/src/mesh.rs:589-592) sets only `database.type/sqlite.path` and no WAL or autocheckpoint key, so headscale is on ITS OWN defaults, whatever v0.23.0 chooses — I did not read headscale's source to establish that value. NONE OF THIS CHANGES THE VERDICT: the restart path's frequency only matters if the restart path is correct and reachable, and Findings 1 and 2 say it is neither. The cost number is filed so R858-B19 can size its own fix, not because it gates the decision.")
//! @yah:handoff("WHAT THIS MEANS FOR R858'S PAYOFF, stated so nobody over-reads the verdict. Adopting turso-backup for HYDRATION ALONE does NOT delete the litestream pin: litestream stays as the replicate daemon, so the 0.3.13 pin, the third-party download and the hand-computed checksums all remain. The pin only goes away if R858-B18 and R858-B19 are both fixed. So the payoff this spike was asked to size is REAL BUT DEFERRED — R858-F17 is worth taking now because failover restore is the leg that actually hurt on 2026-09-03, not because it retires the pin.")
//! @yah:verify("BASELINES, measured before and after in oss/turso-backup (its own Cargo workspace and its own target dir, so no camp target-lock contention). `cargo test --all-targets`: 149 passed / 0 failed both before and after the change — 133 lib + 5 hydrate bin + 4 snapshot bin + 7 rss_harness + 0 tail_sweep_harness, plus the new example target contributing 0 tests. `cargo clippy --all-targets -- --deny=warnings`: clean, exit 0, both before and after. No production source file was modified, so no behaviour was at risk; the baselines are here to prove the new example target did not break the crate's own gates.")
//! @yah:verify("ASSUMPTION DISCHARGED — and it was wrong in the optimistic direction, which is why this is called out rather than left to be inferred from the handoff. The filed @yah:assumes said the restart mechanism \"exists\" and had merely \"never been exercised\", and guessed from the 8.4 MB WAL that the restart path \"may be rare\". Measured: the mechanism does not fire at all in the regime that matters (a writer process restart resets checkpoint_seq to 0, so the Restarted branch is never taken — Finding 2), and locally the fold rate is one per ~375 writes, i.e. frequent rather than rare. The live-headscale fold rate remains genuinely unmeasured; only the local one is established.")

use anyhow::Result;
use std::path::Path;

/// Name of the litestream replicate systemd unit.
pub const LITESTREAM_UNIT: &str = "litestream-headscale.service";
/// Default litestream config path on the machine.
///
/// Under yubaba's own state directory, NOT `/etc` — and that is a correctness
/// requirement, not tidiness. `yubaba.service` runs with
/// `ProtectSystem=strict`, which mounts the whole hierarchy read-only except
/// the paths it names; `/var/lib/yah/yubaba` is granted (`StateDirectory` +
/// `ReadWritePaths`) and `/etc` is not. This file was at
/// `/etc/yah-cloud/litestream.yml` until R858, where every write of it failed
/// EROFS on a fleet node and [`install`]'s `Err` was absorbed by
/// `leader::on_became_leader` into a `warn!` — the fourth way this path
/// contrived to replicate nothing while looking wired.
///
/// `templates/mirror.yml` already states the constraint for the other half of
/// this pair: "yubaba runs under ProtectSystem=strict and CANNOT write
/// /etc/systemd/system or /etc/ufw", which is why the *unit* is pre-staged at
/// provision time and only the config is written here.
pub const LITESTREAM_CONFIG_PATH: &str = "/var/lib/yah/yubaba/litestream.yml";

/// Every key under a replica entry sits at this indent — `- url:` is at 6, so
/// its sibling keys are at 8. Named because the bug this constant replaced was
/// invisible: a `\` line-continuation in the old format string stripped the
/// leading whitespace of the following line, so `access-key-id` came out at
/// column 0 and the replica had no credentials at all (R591-T3).
const REPLICA_KEY_INDENT: &str = "        ";

/// Generate a litestream config YAML for replicating `headscale_db` to `s3_url`.
///
/// The `?endpoint=` query parameter in `s3_url` is extracted and written as a
/// separate `endpoint:` key in the replica config.
///
/// @yah:ticket(R858-B19, "tail_frames restart detection is blind to a WAL recreate: checkpoint_seq resets to 0 and two WAL generations get spliced into one chain")
/// @yah:status(review)
/// @yah:at(2026-09-10T06:47:39Z)
/// @yah:assignee(agent:bundle-anthropic-ashguard)
/// @yah:parent(R858)
/// @yah:severity(high)
/// @yah:next("THE FIX THE MEASUREMENT POINTS AT: carry the WAL header SALT in the watermark and treat a salt change as a restart. The salt moved in EVERY observed fold, in both regimes — on a WAL recreate it is fresh randomness (measured b83c03f5 -> 9ca89e39, unrelated), and on an in-process autocheckpoint salt1 increments in lockstep with checkpoint_seq (measured d492ed8a -> d492ed8b -> ... -> d492ed92 alongside seq 0 -> 8). checkpoint_seq alone is sound only in the second regime; (salt1, salt2) is sound in both. The example's `wal_hdr` already parses the 32-byte WAL header if you need a reference.")
/// @yah:verify("`cd oss/turso-backup && cargo run --example foreign_checkpoint_probe -- b f`. TODAY (bug present) probe B prints 'SILENT WRONG IMAGE' (restored 9 rows against a 12-row source, integrity_check ok, no error raised anywhere) and probe F prints 'restored image UNREADABLE by upstream sqlite3: database disk image is malformed (11)' while restore_latest_stream itself reported success with frames_replayed 57 / generations 2. FIXED means both print a loud refusal or a correct image — never a silent wrong one.")
/// @yah:gotcha("REAL EDIT TARGET IS oss/turso-backup/src/stream.rs — a SUBCAMP, pruned from this board's scan set, which is the only reason this annotation is homed on the yubaba side. Touch `Watermark` (stream.rs:204), `tail_frames`'s start_frame decision (stream.rs:842-846) and `validate_generation_chain` (stream.rs:~1239). THE DEFECT: `Watermark` is `(checkpoint_seq, last_frame)` and `tail_frames` treats an UNCHANGED checkpoint_seq as 'same WAL, resume at last_frame+1'. That inference is false. MEASURED 2026-09-06 by @Ashguard:griffin (session:d27ac15b) with oss/turso-backup/examples/foreign_checkpoint_probe.rs, writer = system sqlite3 3.51.0: when the LAST connection to a DB closes, SQLite checkpoints and DELETES the WAL file, and the next writer creates a fresh WAL whose checkpoint-sequence is back to 0 with a brand-new random salt. So across a writer process restart checkpoint_seq goes 0 -> 0 while the WAL is a completely different one. The `Restarted` branch never fires and the sink silently splices frames from two WAL generations into one generation chain.")
/// @yah:assumes("That the same reset shape occurs when the WRITER IS TURSO rather than upstream C SQLite — i.e. that this bug is general and not foreign-writer-only. NOT MEASURED. The probe drove every writer with the system sqlite3 binary on purpose (a turso-driven probe would have been circular for R858-S6's question). Before sizing the blast radius for in-tree consumers like roadcase, measure the turso-writer-across-process-restart case directly; if turso never recreates its WAL, this is foreign-writer-only and the priority drops.")
/// @yah:handoff("FIXED AND MEASURED 2026-09-09 by @Ashguard:dragon (session:4bd2dae2). All edits in oss/turso-backup ONLY (src/stream.rs, src/puller.rs, examples/foreign_checkpoint_probe.rs); yubaba/litestream.rs untouched, B18 untouched. THE FIX: WAL generation identity is now (checkpoint_seq, salt), not checkpoint_seq. New public types in stream.rs: WalSalt{salt1,salt2} (Display as '{:08x}/{:08x}') and WalGeneration{checkpoint_seq, salt: Option<WalSalt>} with is_provably_same_as() — which is FALSE whenever either side's salt is None, so 'unknown' can never be mistaken for 'unchanged'. tail_frames now resumes at last_frame+1 only when the live generation is PROVABLY the sidecar's; anything else restarts at frame 1.")
/// @yah:handoff("WHERE THE SALT COMES FROM, and why it is not the WAL header: turso_core::WalState (types.rs:3279, verified in the 0.7.2 registry source) exposes ONLY checkpoint_seq_no and max_frame, so the seam cannot report a salt from wal_state(). Reading the -wal file directly would need a path CoreWalSeam::from_conn does not have (oss/roadcase/crates/roadcase-cell/src/durable.rs:773 constructs it that way). So the new read_wal_salt(seam, page_size, last_frame) helper pulls the salt out of FRAME 1's header (bytes 8..16), which SQLite copies verbatim from the WAL header's bytes 16..24 — same value, reached through machinery every WalSeam already implements, including roadcase's connection-backed seam and every mock. Confirmed empirically: the salts tail_frames recorded match the probe's independent on-disk wal_hdr read exactly, e.g. probe B pre-tail 'salt c215c41e/4b3d9657' == the Restarted outcome's previous_generation. Cost is one page-sized local read per tail call. Returns None only for a zero-frame WAL, which takes the Empty return anyway.")
/// @yah:handoff("WATERMARK SHAPE — decided per the ticket's 'break it' default, with ONE deliberate limit. The persisted sidecar changed: 'seq last_frame nanos epoch ptr_gen' gained positional fields 6 and 7 (salt1 salt2), read as a PAIR (salt1 with no salt2 is rejected as a torn write, not downgraded to unknown). PersistedWatermark (crate-private) gained `generation: WalGeneration`. A pre-salt sidecar parses with salt None => forces exactly ONE full re-upload, after which the sink carries a salt and the stream self-heals; test `a_saltless_legacy_watermark_forces_a_restart_rather_than_a_resume` pins both halves. THE LIMIT: the PUBLIC `Watermark` struct still has only {checkpoint_seq, last_frame} and did NOT gain a salt field. Adding one would break struct literals in three oss/yubaba test mocks (tests/rebuild_drill.rs:102, tests/integration_mesh.rs:409, tests/raft_rebuild_fencing.rs:110) plus tenant-streamer/src/streamer.rs:259, and this ticket was explicitly scoped out of oss/yubaba. Nothing is lost — generation identity lives in WalGeneration and is what every comparison uses — but `Watermark`'s doc comment, which LITERALLY CLAIMED 'checkpoint_seq_no increments monotonically across restarts' (the false premise that caused this bug), is now rewritten to say the opposite and point at WalGeneration. If someone later wants salt on the public Watermark, it is a 4-line mechanical edit in yubaba.")
/// @yah:handoff("RESTORE SIDE — validate_generation_chain now REFUSES what it cannot prove, which is the half of the ticket that kills the silent wrong image. Generation manifests moved to header 'TURSO-BACKUP STREAM v4' carrying a `wal_salt <salt1>-<salt2>` line (GenerationManifest/OwnedGenerationManifest gained `salt: Option<WalSalt>`; ValidatedChain's `checkpoint_seq: u32` became `generation: WalGeneration`). Parser guards BOTH directions, same reasoning as the existing v2-epoch guard: a v4 header without wal_salt is corrupt (not legacy), and a pre-v4 header WITH one is forged (so a hand-added line cannot wave a spliced chain through). The chain rules: (1) a chain of 2+ manifests where ANY lacks a salt is REFUSED — that shape is exactly what a pre-R858-B19 writer produced and nothing in it records which WAL each range came from; (2) 2+ manifests with disagreeing salts are REFUSED, naming both salts and the shared checkpoint_seq; (3) a SINGLE manifest is still accepted with any salt including none, because one generation cannot be a splice and refusing it would strand every legacy single-generation backup for no safety gain. WalPuller got the same widening (it fans frames onto LIVE appliers, so it must stop harder than restore): puller.rs now compares chain.generation.is_provably_same_as(prior) instead of checkpoint_seq equality, with a new `pulled_generation` field beside `pulled`.")
/// @yah:handoff("DISCOVERED AND FIXED IN THE SAME PASS, not filed as a followup: the ticket's fold happens BETWEEN two tail calls, but nothing stopped one landing INSIDE one. tail_frames sampled the generation once, before the drain, so a WAL recreated mid-drain uploaded a mix of two WALs that no watermark comparison could ever see. tail_frames now re-reads the salt after the drain and before the watermark CAS, and bails loudly if it moved. Refusing there is complete rather than partial: the watermark has not advanced and no manifest exists, so whatever frames landed are orphaned under keys nothing references — invisible to restore, exactly like the existing Shed path — and the next tail restarts cleanly. Pinned by `a_wal_recreated_mid_drain_publishes_nothing`, which asserts the sink has neither a watermark nor a manifest afterwards.")
/// @yah:handoff("MEASURED BEFORE AND AFTER, both by me on this machine, /usr/bin/sqlite3 3.51.0. BASELINE (own run, pre-edit, reproduces the ticket verbatim): probe B 'VERDICT[b]: SILENT WRONG IMAGE — restored t=9/12, integrity Ok(\"ok\"). No error was raised anywhere', tail#2 returned Empty and restore succeeded off generation 1 alone; probe F 'restored image UNREADABLE by upstream sqlite3: database disk image is malformed (11)' with restore_latest_stream reporting success, frames_replayed 57 / generations 2. cargo test 151 passed / 0 failed (135 lib + 5 hydrate + 4 snapshot + 7 rss_harness). AFTER: probe B and probe F BOTH print 'restore REFUSED (fail-loud): generation #1 was written under WAL salt X but the chain starts at salt Y (both at checkpoint_seq 0) — the source WAL was RECREATED mid-stream...' => 'VERDICT: safe-but-stalled', and both now report 'restart signalled? true' with Restarted naming both generations. cargo test 158 passed / 0 failed (142 lib + 5 + 4 + 7), i.e. +7 lib tests, zero regressions. cargo clippy --all-targets exits 0.")
/// @yah:handoff("TWO PRE-EXISTING TESTS CHANGED THEIR EXPECTED OUTCOME, both deliberately, both with the reasoning written at the call site so nobody 'fixes' them back. (1) `rpo_legacy_two_field_sidecar_parses_and_upgrades` asserted Streamed/first_frame==2 ('resumes after the legacy watermark'); it now asserts Restarted/first_frame==1, because a two-field sidecar records no salt and resuming on it is the exact inference this ticket deletes. Its actual subject — an unknown RPO age is not a breach — is untouched and still asserted. (2) `a_chain_straddling_the_batching_change_replays_as_one_stream` asserted validate_generation_chain(...).expect(\"layout is not a chain property\"); it now asserts the 'no WAL salt' refusal. Layout still is not a chain property (the replay assertion below it is unchanged and still passes); what changed is PROVENANCE — that fixture is a two-generation chain of a v2 and a v3 manifest, both necessarily saltless, which is byte-for-byte the shape a WAL recreate produced. A chain that old now needs a fresh tier-1a snapshot; one generation of it still restores.")
/// @yah:handoff("BLAST RADIUS OUTSIDE turso-backup — checked, and one thing I could NOT verify. Nothing outside the crate constructs GenerationManifest, reads OwnedGenerationManifest.salt, or matches StreamOutcome::Restarted by field name (grepped oss/yubaba, oss/roadcase, oss/kamaji, crates, app). The out-of-scope WalSeam mocks (yubaba rebuild_drill.rs:107, integration_mesh.rs, raft_rebuild_fencing.rs, tenant-streamer/src/streamer.rs:261) all serve frame 1 whenever last_frame>=1 and zero bytes 8..16, so they report a stable salt of (0,0) and keep resuming exactly as before — read directly, not inferred. NOT VERIFIED BY COMPILE: `cargo check -p yubaba --tests` currently fails on 3 unrelated errors — 'missing field `files` in initializer of WorkloadSpec' at headscale_appliance.rs:285, pond/launcher.rs:140, cloud/src/reconciler/native_support.rs:71 — which are @Ashguard:coffee's (session:967e5e1d) in-flight R870 WorkloadSpec change, not mine, and I left them alone per shared-tree. So yubaba's consumers of this crate are verified by grep + reading the mocks, NOT by a green build; re-run that check once R870 lands. roadcase was not compiled either (separate workspace, same reasoning: it uses CoreWalSeam, whose trait surface is unchanged).")
/// @yah:next("OPEN QUESTION THIS TICKET DID NOT ANSWER (unchanged from the original @yah:assumes): whether a TURSO writer recreates its WAL across a process restart the way upstream C SQLite does. Still NOT MEASURED — every probe here drives the writer with the system sqlite3 binary on purpose. The fix is writer-agnostic (it reads the salt off the frames, whoever wrote them), so nothing is wrong if turso never recreates; it would only mean the bug was foreign-writer-only and the priority was overstated. Worth measuring before sizing in-tree consumers like roadcase.")
/// @yah:verify("cd oss/turso-backup && cargo run --example foreign_checkpoint_probe -- b f — BOTH probes must print 'restore REFUSED (fail-loud)' naming two different WAL salts at the same checkpoint_seq, and 'restart signalled? true'. A 'SILENT WRONG IMAGE' or 'UNREADABLE by upstream sqlite3' verdict means the salt check was removed or bypassed.")
/// @yah:handoff("Ready for sign-off. Tree state: uncommitted (camp git policy is defer — no commit was made, so there is no SHA to anchor to). Files changed: oss/turso-backup/src/stream.rs, oss/turso-backup/src/puller.rs, oss/turso-backup/examples/foreign_checkpoint_probe.rs (short()'s Restarted arm, the only edit to the probe — its measurement logic and verdicts are untouched so the before/after comparison is like-for-like).")
/// @yah:verify("RE-RUN BY THE LEADER (@Ashguard:hydra, session:ee099a8e), not taken from the courier's word. `cd oss/turso-backup && cargo test` = 158 passed / 0 failed across all five targets (142 lib + 5 + 4 + 7 + 0), matching the claimed 151 -> 158 delta exactly. `cargo run --example foreign_checkpoint_probe -- b f`: BOTH probes now print 'restart signalled? true' and 'restore REFUSED (fail-loud): generation #1 was written under WAL salt X but the chain starts at salt Y (both at checkpoint_seq 0)' with the salts named (B: d3a561eb/f1c80ff2 -> 4128ec52/0cedb775; F: 869b0051/f439c2fb -> 97a80a11/dd50a9a7), verdict 'safe-but-stalled'. Neither SILENT WRONG IMAGE nor UNREADABLE appears. INDEPENDENTLY CONFIRMED THE COURIER'S PEER-ATTRIBUTION rather than accepting it: `git diff --stat oss/yah-base/crates/workload-spec/src/lib.rs` shows +55 uncommitted lines adding `pub files: Vec<InlineFile>` to WorkloadSpec, so the three `missing field files` errors blocking `cargo check -p yubaba --tests` really are @Ashguard:coffee's in-flight R870 change and not this ticket's — leaving them alone was correct.")
/// @yah:gotcha("'SAFE-BUT-STALLED' IS THE RIGHT VERDICT AND IT EXPOSES A PRE-EXISTING GAP THIS TICKET DID NOT CREATE — checked by the leader before signing off, because a refusal that strands every restore would be a worse bug than the splice. IT DOES NOT: `git show 6f984b53a9dd1a291d29fe7d4cb544b47d4f65e6:oss/turso-backup/src/stream.rs` line 1281 already refused a chain whose manifests disagree on checkpoint_seq, with the SAME message ('WAL restart between generations, restore needs a fresh tier-1a snapshot'), and the module's own R-handoff at :114 states that refusal as deliberate design ('heroic restart-spanning replay would silently corrupt'). B19 extends an existing refusal to the case that was slipping past it; it introduces no new stall class. THE GAP, WHICH IS REAL AND OLDER THAN THIS TICKET: nothing in production takes the fresh tier-1a snapshot the refusal asks for. `snapshot_and_upload` has no caller outside this crate's tests and the standalone `turso-backup-snapshot` bin — so a base snapshot is an operator/cron act. And the one live streaming consumer, oss/yubaba/crates/tenant-streamer/src/main.rs:465, folds `Restarted` into the SAME match arm as `Streamed` and just logs 'streamed'. So after any writer-process restart the stream-tier replica is unrestorable until somebody runs the snapshot bin, and the log says nothing about it. THIS MATTERS DIRECTLY TO R858: headscale restarts on every failover and every yubaba redeploy, so a headscale stream-tier tail would cross a WAL recreate routinely. Whoever builds that tail (R850's unbuilt option A or B, named in oss/yubaba/crates/cloud/src/topology.rs's next) must trigger a base snapshot on Restarted rather than logging it as an ordinary stream.")
/// @yah:verify("THE COURIER'S OPEN COMPILE GAP IS NOW HALF-CLOSED, AND ITS STATED CAUSE IS STALE — corrected by the leader (@Ashguard:hydra) so nobody re-runs the wrong command. The courier could not compile yubaba and attributed it to @Ashguard:coffee's R870 `missing field files in initializer of WorkloadSpec`; that attribution was right at the time and I confirmed it independently, but those three errors are GONE now. `cargo check -p yubaba --lib` = EXIT 0, clean — so yubaba's LIBRARY consumers of turso-backup compile against B19's (checkpoint_seq, salt) generation identity and B18's open_reader, which is the half that was only grep-verified before. `cargo check -p yubaba --tests` STILL fails, but on a DIFFERENT peer's in-flight file: `cannot find module or crate libc` at oss/kamaji/crates/kamaji-bin/src/tail.rs:107 (two occurrences) plus an unused `std::path::PathBuf` import at :42 — that is @Ashguard:eclipse's R850-F1 tail work, landing live, and it reaches yubaba's test build through the kamaji-bin dev-dependency. Left untouched per shared-tree. SO THE RESIDUAL IS NARROW AND SPECIFIC: the three WalSeam mocks in yubaba's own test files (tests/rebuild_drill.rs:107, tests/integration_mesh.rs, tests/raft_rebuild_fencing.rs) plus tenant-streamer/src/streamer.rs:261 are still verified by reading them rather than by a green build. Re-run `cargo check -p yubaba --tests` once R850's tail.rs compiles — NOT \"once R870 lands\", which is what the earlier note says and is no longer the blocker.")
pub fn generate_config(headscale_db: &Path, s3_url: &str) -> String {
    let (url_without_query, endpoint) = split_s3_url(s3_url);
    let mut out = String::from("---\ndbs:\n");
    out.push_str(&format!("  - path: {}\n", headscale_db.display()));
    out.push_str("    replicas:\n");
    out.push_str(&format!("      - url: {url_without_query}\n"));
    if let Some(ep) = endpoint {
        out.push_str(&format!("{REPLICA_KEY_INDENT}endpoint: {ep}\n"));
    }
    // Credentials are env-expanded by litestream itself, so the config file is
    // safe to write world-readable and safe to put in a bug report.
    out.push_str(&format!(
        "{REPLICA_KEY_INDENT}access-key-id: ${{LITESTREAM_ACCESS_KEY_ID}}\n"
    ));
    out.push_str(&format!(
        "{REPLICA_KEY_INDENT}secret-access-key: ${{LITESTREAM_SECRET_ACCESS_KEY}}\n"
    ));
    out
}

/// Write the litestream config to [`LITESTREAM_CONFIG_PATH`] (idempotent).
///
/// Credentials are read from `LITESTREAM_ACCESS_KEY_ID` /
/// `LITESTREAM_SECRET_ACCESS_KEY` in the environment — inject via
/// `/etc/yah-cloud/litestream.env`, which `litestream-headscale.service` reads
/// with `EnvironmentFile=-` and `yubaba.service` reads for
/// `YUBABA_LITESTREAM_S3_URL`. One file, both readers, because a URL without
/// the credentials that authenticate to it replicates nothing.
///
/// # The config only. The unit ships at provision time
///
/// This function used to write `/etc/systemd/system/litestream-headscale.service`
/// too, and could not: `yubaba.service` sets `ProtectSystem=strict` and grants
/// no path under `/etc`, so both that write and the config write (then also
/// under `/etc`) failed EROFS on every fleet node, and
/// `leader::on_became_leader` absorbed the `Err` into a `warn!`. R591-T3 found
/// three ways this path replicated nothing while looking wired; this was the
/// fourth, and it defeated the other three's fixes.
///
/// The unit is static text, so it needs no writer at all — it is shipped in
/// the release tarball beside `yubaba.service` and laid down by cloud-init,
/// the same treatment `templates/mirror.yml` already gives `headscale.service`
/// for exactly this reason. What genuinely varies per node is the S3 URL, and
/// that is all this function now writes.
///
/// # Call this before the replicate unit starts (R591-T3)
///
/// The replicate unit runs `litestream -config <LITESTREAM_CONFIG_PATH>`.
/// Until R591-T3 nothing called this function at all, so that file never
/// existed on any node: `systemctl start litestream-headscale.service` failed
/// against a unit that had never been written, and the failure was absorbed
/// into a discarded exit status. (Restore used to read the same config —
/// R858-F17 replaced that leg with kamaji's hydrate-on-place, which reads
/// `crate::headscale_appliance`'s `yah.durability.store` instead, not this
/// file.)
///
/// @yah:ticket(R858-F17, "Hydrate headscale's sqlite DB from turso-backup before headscale starts (replaces litestream's restore leg)")
/// @yah:status(review)
/// @yah:at(2026-09-10T08:26:00Z)
/// @yah:assignee(agent:bundle-anthropic-miravel)
/// @yah:parent(R858)
/// @yah:next("DO NOT ALSO MOVE THE IDENTITY FILE IN THIS TICKET. R858's acceptance-test gotcha leg (2) — noise_private.key, 72 bytes, local disk only — is a separate unreplicated-state problem that turso-backup does not solve either. It is R600/W273's cluster secret store. Conflating them is how this ticket grows past its safe scope.")
/// @yah:verify("Reproduce probe C first so the premise is yours and not inherited: `cd oss/turso-backup && cargo run --example foreign_checkpoint_probe -- c`. Expect 'C VERDICT: CORRECT' and an unperturbed source line at C3.")
/// @yah:gotcha("GREEN LIGHT, AND IT IS THE ONLY GREEN HALF OF R858-S6. Hydration needs NO foreign-process interaction whatsoever, which is exactly why it is safe while the replication leg (R858-S6's other follow-ons) is not: the sequence is fetch base snapshot + replay frames -> write a plain sqlite file at headscale's `database.sqlite.path` -> THEN start headscale. Nothing else has the file open at that moment, so the whole-file exclusive lock that blocks the streaming leg is a non-issue here. MEASURED 2026-09-06 by @Ashguard:griffin (session:d27ac15b), probe C in oss/turso-backup/examples/foreign_checkpoint_probe.rs: a WAL written by upstream C sqlite 3.51.0 and left uncheckpointed (writer SIGKILLed) copies through `raw_consistent_copy_live` to an 8192-byte image that upstream sqlite3 reads with `PRAGMA integrity_check` = ok and the exact live row count, with NO -wal sidecar needed. The source was verified unperturbed by the copy (identical WAL salt and max_frame before and after).")
/// @yah:assumes("That headscale reads a hydrated plain-sqlite image with no -wal sidecar present at startup. Grounded — the image is vanilla SQLite and probe C read it with upstream sqlite3 — but not verified against a running headscale, and no live box was touched by R858-S6.")
/// @yah:gotcha("THIS TICKET CANNOT DELIVER VALUE ON ITS OWN — IT IS BLOCKED ON R858-B18, and the reason is a format-coherence argument nobody on this relay had made. Measured by reading Cargo.tomls and call sites 2026-09-09 (@Ashguard:hydra, session:ee099a8e): NOTHING IN THE FLEET WRITES turso-backup-FORMAT BYTES FOR HEADSCALE, so a hydrate would read an empty prefix and the helper would exit 0 with 'nothing_in_the_store' — starting headscale on an EMPTY DB, which is strictly worse than the litestream restore it replaces. THE THREE FACTS: (1) oss/yubaba/crates/yubaba/Cargo.toml:160 has turso-backup under [dev-dependencies] ONLY, with the comment 'the yubaba server links neither it nor turso-backup at runtime — W253 tenet 1'; (2) kamaji does not link it either — it EXECS turso-backup-hydrate (oss/kamaji/crates/kamaji-bin/src/hydrate.rs, R850-F1), and hydrate is the only helper that exists: the tail-side binary is R850's own unbuilt option (B) in oss/yubaba/crates/cloud/src/topology.rs's next; (3) litestream writes litestream's format, turso-backup reads turso-backup's. So 'replace only the restore leg' splits a format in half. AND THE WRITE SIDE IS EXACTLY WHAT B18 BLOCKS, for BOTH tiers, not just the stream tier the spike measured: snapshot.rs:281 opens the source with turso::Builder::new_local before VACUUM INTO, which is the same engine and therefore the same whole-file exclusive lock that refused CoreWalSeam::open. Against a live headscale, turso-backup can neither tail nor snapshot. DO B18 FIRST.")
/// @yah:gotcha("WHEN B18 UNBLOCKS THIS, DO NOT ADD A HYDRATE CALL TO yubaba's leader PATH — the wiring already exists and a second site is the defect this relay has now spent two tickets collapsing (R858-B9's three-way port disagreement, R858-T16's renderer). READ oss/kamaji/crates/kamaji-bin/src/server.rs:1904 FIRST: kamaji already runs hydrate-on-place for EVERY deploy, and it is deliberately sited BEFORE the `spec.wants_native_exec()` branch at :1919 — its own comment says 'a durability guard a workload can dodge by setting yah.exec = native is not a guard'. headscale is a native workload and it passes straight through that gate today, inert only because its spec declares no tier. SO THE CHANGE IS A DECLARATION, NOT A CALL: put yah.durability.tier / .subjects / .store on the headscale WorkloadSpec yubaba builds, and litestream::restore (oss/yubaba/crates/yubaba/src/litestream.rs:282) is DELETED rather than replaced. ONE OBSTACLE, and it has a clean answer: hydrate::plan (kamaji-bin/src/hydrate.rs:99-108) demands exactly one VolumeSource::Named and renders volume_root as VOLUME_ROOT/<name> = /var/lib/yah/kamaji/volumes/<name>, which a native workload does not have — headscale's state is /var/lib/yah-cloud/headscale/. Widen `plan` (and workload_spec::validate::shape's matching rule) to accept exactly one Named OR ONE VolumeSource::Bind{host_path} for a bytes-shipping tier, resolving Bind to its host_path; Bind is already gated to tier=='infra' (workload-spec/src/lib.rs:4027-4029), which headscale is. Do NOT instead migrate headscale's live state dir under the kamaji volume root — that dir holds the hand-edited config.yaml, noise_private.key and acme-cache on prod, and moving it is a live-state migration far past this ticket's own scope warning. SEQUENCING HAZARD, WRITE IT INTO THE RELEASE NOTE: the moment the spec declares a tier, hydrate::run REFUSES the deploy on any kamaji started without --hydrate-helper (kamaji-bin/src/hydrate.rs:170-178), and NO prod node has that flag or the turso-backup-hydrate binary today. The helper and the flag must reach every candidate node (mirror.yml + the release tarball, the same way R858 already had to ship the litestream binary and unit) in a release that lands BEFORE the one carrying the declaration.")
/// @yah:notify_on(R850, "R850's tail (turso-backup-tail + kamaji --tail-helper, @Ashguard:eclipse) is the write side this ticket hydrates FROM — until it lands, a hydrate reads an empty prefix and starts the coordination server on an empty database. When R850 reaches review: (1) re-read this ticket's two leader gotchas, they carry the whole implementation with file:line; (2) check whether eclipse took the VolumeSource::Bind widening into R850 or left it here — headscale is native-exec with no named volume, and both hydrate::plan (kamaji-bin/src/hydrate.rs:99-108) and workload_spec::validate::shape (validate.rs:588-597) demand exactly one Named volume today; (3) then the change is a DECLARATION on the headscale WorkloadSpec plus DELETING litestream::restore (oss/yubaba/crates/yubaba/src/litestream.rs:282), not a new call site.")
/// @yah:gotcha("DEPENDS_ON(R850) CLEARED 2026-09-10 — BOTH BLOCKERS THIS TICKET HAD ARE GONE, AND THE EARLIER GOTCHAS ARE NOW PARTLY STALE. (1) The write side EXISTS. @Ashguard:eclipse landed R850-F1's backup half while this relay was running: `turso_backup::tail` (start/round), the `turso-backup-tail` binary (oss/turso-backup/Cargo.toml:82, src/bin/tail.rs), and kamaji-bin/src/tail.rs supervising one per declaring workload behind a new `--tail-helper` / KAMAJI_TAIL_HELPER. So the 'nothing writes turso-backup-format bytes for headscale' gotcha above is now FALSE — declaring a tier arms BOTH the hydrate and the tail. Their exit code 2 means FENCED and kamaji stops the workload on it, which is the at-most-one-live property this relay wants for a coordination server. (2) The Bind widening I specified is ALREADY DONE, by eclipse, in R850 rather than here — I asked and they took it. Do NOT re-do it: hydrate::plan now resolves `VolumeSource::Bind { host_path }` to its own host_path (kamaji-bin/src/hydrate.rs:108) and workload_spec::validate::shape counts named-or-bind (validate.rs:602), both citing R858-F17 by name, with Tmpfs deliberately excluded because it is the declaration that the data does not survive. WHAT REMAINS IS ENTIRELY IN oss/yubaba. THE ONE THING THAT DID NOT CHANGE, AND IT IS THE DANGEROUS ONE: the moment the headscale spec declares a tier, kamaji REFUSES the deploy on any node started without the helpers (hydrate.rs:170-178), and NO prod node has them. A release carrying the declaration but not the binaries+flags decapitates the mesh on the next roll — which is the exact failure this whole relay exists for. The binaries and the flags must reach every candidate node in a release that lands BEFORE the one carrying the declaration.")
/// @yah:notify_on(R850-F1, "R850-F1 landed the two things this ticket was blocked on. (1) THE BACKUP SIDE EXISTS: `turso_backup::tail` + the `turso-backup-tail` binary + `kamaji-bin/src/tail.rs` supervising one per declaring workload, so headscale's prefix stops being empty as soon as the appliance declares a tier — a hydrate no longer reads `nothing_in_the_store` forever. (2) THE BIND WIDENING IS DONE, as @Ashguard:hydra and @Ashguard:eclipse agreed it should land here: `hydrate::plan` and `workload_spec::validate::shape` both now accept exactly one Named OR one Bind for a bytes-shipping tier, and a Bind resolves to its own host_path rather than being rehomed under VOLUME_ROOT. Tmpfs is deliberately not a candidate. Tests: `a_bind_volume_resolves_to_its_own_host_path` (kamaji), `a_bind_volume_is_a_legitimate_root_for_subjects` + `one_named_plus_one_bind_is_still_ambiguous` (workload-spec shape_fixtures). NOTE a bind is separately gated to workload `tier = \"infra\"` — headscale qualifies, and the two rules compose. ALSO: the tail's exit code 2 means FENCED and kamaji stops the workload on it; for a coordination server that is the behaviour you want when a stale node comes back, and it is new, so read `kamaji-bin/src/tail.rs`'s module doc before wiring headscale up.")
/// @yah:handoff("Tree anchor at write time: 4740623c73297188d4265608265996025ba30cd3 (dirty, uncommitted — nothing here is a revert instruction; litestream::restore below names the deleted FUNCTION, not an action to take). LANDED, oss/yubaba only, exactly as the leader's third gotcha specified: a DECLARATION plus a deletion, no new call site. (1) headscale_appliance.rs::appliance_spec now carries yah.durability.tier=stream, .engine=turso, .store=s3://yah-headscale/appliance/headscale (new HEADSCALE_DURABILITY_STORE const, distinct from litestream's s3://yah-headscale/headscale prefix), .subjects=headscale.db. tier=infra and the one VolumeSource::Bind{headscale_dir} were already present, confirmed not assumed. (2) litestream.rs: the functions litestream::restore and litestream::restore_args, plus their 3 unit tests, were removed entirely; litestream::install and the replicate litestream::start/litestream::stop are UNCHANGED and keep running on litestream's own prefix (deliberate transition, not a shim — see next handoff entry). Module docs plus 3 stale intra-doc links to the now-gone function were updated to describe the split. (3) leader.rs::on_became_leader step 1 no longer calls the now-deleted function; step 2 comment now says kamaji hydrates headscale.db via the WorkloadSpec's durability declaration before forking the appliance. (4) mirror.yml: added cp of turso-backup-hydrate/turso-backup-tail from the yubaba tarball to /usr/local/bin (tolerant of absence -- logs to stderr and continues, since the tarball does not carry them yet), chmod +x, and a NEW kamaji.service.d/50-durability-helpers.conf drop-in setting KAMAJI_HYDRATE_HELPER/KAMAJI_TAIL_HELPER as Environment= (never ExecStart=, per kamaji.service's own warning about the pre-existing 20-bundle.conf ExecStart-clobber hazard from the 2026-09-03 outage) -- only written when both binaries are present, so a node provisioned before the tarball carries them boots exactly as today.")
/// @yah:handoff("SCOPE BOUNDARY I HELD, NOT AN OMISSION: scripts/publish-yubaba-release.sh (top-level, outside oss/yubaba, a signed-artifact release/publish script) was NOT touched, per this ticket's own 'YOUR SCOPE IS oss/yubaba AND NOTHING ELSE'. It still needs the build+package+version-gate treatment already given kamaji (scripts/cross-build-guarded.sh -p turso-backup-hydrate / -p turso-backup-tail for both musl triples, staged into the tarball root, version-lockstep-checked the way scryer/passway already are around lines 118-137 of that script) so mirror.yml's cp actually finds the binaries. Until that lands, mirror.yml's new steps are harmless no-ops (present-checked, non-fatal) and the sequencing hazard the ticket warns about cannot yet fire -- nothing today declares a tier, and now that headscale does, no node has the helpers, so rolling THIS change alone would refuse headscale's deploy everywhere. publish-yubaba-release.sh's fix, and a rollout of that release, must land and reach every candidate node FIRST, exactly as the ticket's own release-order instruction says.")
/// @yah:next("OPERATOR RELEASE ORDER (restated per the ticket's own ask): once publish-yubaba-release.sh is extended to bundle turso-backup-hydrate + turso-backup-tail, cut and roll THAT release to every candidate node FIRST (verify via ssh: /usr/local/bin/turso-backup-hydrate and turso-backup-tail present, kamaji.service.d/50-durability-helpers.conf present, kamaji restarted with the new env vars). Only THEN cut and roll the release carrying this ticket's headscale_appliance.rs durability declaration. Rolling the declaration first on any node whose kamaji lacks both helpers makes that node refuse to deploy headscale -- the exact fleet-down failure mode this whole relay exists to prevent.")
/// @yah:handoff("VERIFY, measured after edits (leader's own stated baseline: cargo check -p yubaba --lib was EXIT 0 minutes before this session). cargo check -p yubaba --lib: clean, 0 warnings on touched files. cargo test -p yubaba --lib: 950 passed / 0 failed. New test headscale_appliance::tests::the_durability_declaration_shapes_and_plans_to_the_state_dir: asserts workload_spec::validate::shape(&spec) is Ok, and kamaji_bin::hydrate::plan(&spec) yields HydratePlan::Declared with volume_root=/var/lib/yah-cloud/headscale, subjects=[headscale.db], tier=Stream, bucket=yah-headscale, prefix=appliance/headscale -- the whole point per the ticket. cargo clippy -p yubaba --lib: 16 warnings total, all pre-existing (confirmed by grepping the output for litestream.rs / headscale_appliance.rs / leader.rs / mirror.yml -- zero matches). Reproduced probe C fresh: cd oss/turso-backup && cargo run --example foreign_checkpoint_probe -- c -> 'C VERDICT: CORRECT', source unperturbed (identical WAL salt/max_frame in C1 and C3). Did not run cargo test -p yubaba --tests -- kamaji-bin's own lib now compiles clean as of this session (checked separately), but --tests was outside this ticket's asked-for verify and I did not chase it. NOTHING ROLLED, NOTHING COMMITTED -- source change only.")
/// @yah:next("Before the next actual release cut: run scripts/publish-yubaba-release.sh for real (build half at minimum, --skip-build=0 no --publish) on a host where scripts/cross-build-guarded.sh's tool-policy gate does not fire, to prove the musl cross output rather than just the native one this session could reach. Then follow this ticket's standing release-order instruction: roll that release to every candidate node BEFORE the release carrying headscale's durability declaration.")
/// @yah:handoff("Tree anchor at write time: 4740623c73297188d4265608265996025ba30cd3 (dirty, uncommitted). DONE THE THING THE LEADER MADE THE CALL ON: scripts/publish-yubaba-release.sh now builds + packages + version-gates turso-backup-hydrate and turso-backup-tail exactly like kamaji. Version gate added right after the passway check: refuses if oss/turso-backup/Cargo.toml's version != VERSION (matched today, both 0.8.36); added oss/turso-backup to the dirty-tree diff --quiet check. Build loop: two new cross-build-guarded.sh calls, -p turso-backup --bin turso-backup-hydrate and --bin turso-backup-tail (explicit --bin each, not '' -- turso-backup is ONE package with THREE bins including turso-backup-snapshot, which nothing here should ship; explicit --bin is the same shape passway-demux/passway-http-router already use out of a shared crate), workdir oss/turso-backup, no --features (neither bin needs one). Packaging: HYDRATE_BIN/TAIL_BIN path vars added to the existing ELF-check loop and the stage cp line; two new tar -tzf layout assertions alongside the existing passway-graceful-upgrade one. Updated the script's own header comment (steps 4 and 5) to list the new build/package outputs. Updated mirror.yml's two comments the leader flagged as about to go stale ('outside this ticket's declared scope' and 'THIS TARBALL DOES NOT YET CONTAIN THEM') to describe the now-completed state -- did NOT touch the absent-tolerant shell logic itself, per instruction, so an older tarball still provisions cleanly.")
/// @yah:handoff("VERIFY. shellcheck -x scripts/publish-yubaba-release.sh: exit 0, clean -- confirmed the pre-edit baseline was also exit 0 clean (git show HEAD:scripts/publish-yubaba-release.sh piped through the same check), so this introduces no new warnings. Could NOT run the script's actual --publish or even --skip-build=0 path: it fetches release-cosign-key + release-cosign-key-pw from the vault and runs a multi-target cross build, real privileged/heavy work a courier should not take on unprompted, and this session's tool policy independently hard-refused every invocation of scripts/cross-build-guarded.sh itself (all three attempts, plain and with the sandbox override, failed identically with 'tool-policy floor: fail-closed (variable primary, eval, or sub-interpreter with non-literal argument)' -- environmental, not a defect in the script; the missing piece the leader asked me to name if something couldn't be done). What I DID run instead, to ground the plumbing rather than assert it: (1) cd oss/turso-backup && cargo build --release -p turso-backup --bin turso-backup-hydrate --bin turso-backup-tail -- succeeded clean, produced both binaries under oss/turso-backup/target/release/ with exactly the names the script's HYDRATE_BIN/TAIL_BIN vars expect (native arm64 Mach-O, not the musl cross target, since the cross-build-guarded.sh path itself was blocked -- so package name, both --bin names, and the oss/turso-backup workdir are proven, cross-compilation to the actual musl triple is not). (2) cargo test -p yubaba --lib: re-ran fresh, still 950 passed / 0 failed (this pass touches no yubaba/kamaji/turso-backup source, only the release script + a template, so an unchanged count is the expected and correct result, not a skipped check).")
/// @yah:handoff("LANDED IN TWO PASSES by @Miravel:polaris (session:348a9d7c) under @Ashguard:hydra (session:ee099a8e), 2026-09-10. Source-only; nothing committed, nothing rolled, no live node touched. Pass 1: headscale's WorkloadSpec now declares yah.durability.{tier,subjects=headscale.db,store} against its existing single VolumeSource::Bind, litestream::restore and its leader call site are DELETED, and mirror.yml stages both helpers plus the kamaji env-var drop-in. Pass 2 (a warm re-dispatch, because pass 1 deferred it): scripts/publish-yubaba-release.sh now builds, packages and version-gates turso-backup-hydrate and turso-backup-tail exactly as it does kamaji, and mirror.yml's two now-false comments were corrected. THE STORE PREFIX IS DELIBERATELY DISTINCT from litestream's — the two write incompatible on-disk layouts and one prefix would interleave them under the same keys.")
/// @yah:verify("RE-RUN BY THE LEADER, not taken from the courier: `cargo test -p yubaba --lib` = 950 passed / 0 failed, matching the claim exactly, and `cargo check -p yubaba --lib` EXIT 0. The version-lockstep gate the courier added is live-correct today — oss/turso-backup/Cargo.toml:3 and oss/yubaba/Cargo.toml:28 both read 0.8.36, so ws_version agrees and the REFUSED branch stays shut. The cross-build call signature matches scripts/cross-build-guarded.sh's documented 5-positional contract (package, target, bin, features, workdir) argument for argument. The new test asserts the thing that actually matters: the spec yubaba builds passes workload_spec::validate::shape AND hydrate::plan resolves it to volume_root /var/lib/yah-cloud/headscale — a spec that declares a tier and fails plan() is a coordinator that will not deploy.")
/// @yah:gotcha("ONE VERIFICATION GAP, AND NO SESSION UNDER THIS HARNESS CAN CLOSE IT — do not read it as a courier cutting a corner. `scripts/cross-build-guarded.sh turso-backup <triple> turso-backup-hydrate \"\" oss/turso-backup` was never actually EXECUTED. The courier reported its tool policy refusing it; I then ran the identical command myself and got the same refusal verbatim — `tool-policy floor: fail-closed (variable primary, eval, or sub-interpreter with non-literal argument)` — so this is the approval rail, not the agent. WHAT IS THEREFORE PROVEN AND WHAT IS NOT: proven, by a native cargo build, that the package name, both [[bin]] names and the oss/turso-backup workdir resolve; proven by reading that the 5 positional args match the script's documented contract; NOT proven that the musl cross leg emits a working binary. THE SPECIFIC RISK IS REAL RATHER THAN THEORETICAL: cross-build-guarded.sh's own header warns that cross 0.2.5 silently degrades to a HOST build, and a glibc helper in a musl tarball fails at runtime ON THE NODE, not at build time here — which for these two binaries means kamaji refusing to deploy the coordination server. turso_core is also a heavier musl target than anything else in that tarball. RUN THE REAL CROSS-BUILD BEFORE CUTTING A RELEASE that carries these binaries, from a session whose policy permits it. AND THE RELEASE ORDER IS NOT OPTIONAL: the release carrying the helpers and the kamaji drop-in must reach every candidate node BEFORE the release carrying headscale's declaration, or the first roll of the second refuses to deploy the coordinator (kamaji-bin/src/hydrate.rs:170-178).")
pub fn install(headscale_db: &Path, s3_url: &str) -> Result<()> {
    let config = generate_config(headscale_db, s3_url);
    if let Some(parent) = Path::new(LITESTREAM_CONFIG_PATH).parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(LITESTREAM_CONFIG_PATH, &config)?;
    Ok(())
}

/// Start `litestream-headscale.service` (idempotent — no-op if already running).
///
/// @yah:ticket(R858-B18, "turso-backup cannot tail a live foreign-written sqlite DB: turso_core takes a whole-file exclusive lock at open")
/// @yah:status(review)
/// @yah:at(2026-09-10T07:23:52Z)
/// @yah:assignee(agent:bundle-anthropic-ashguard)
/// @yah:parent(R858)
/// @yah:severity(high)
/// @yah:next("UNTIL THIS IS ANSWERED, litestream stays as the replicate daemon and only the restore leg moves (R858-F17). That split is deliberate: hydration is safe and independent, replication is not.")
/// @yah:verify("`cd oss/turso-backup && cargo run --example foreign_checkpoint_probe -- d g`. Expect G2/G3 REFUSED, G3b SUCCEEDED, D2 refused with 'database is locked (5)' against a D0 control that ran in ~4ms.")
/// @yah:gotcha("THE ESCAPE HATCH WORKS BUT IS NOT THE FIX — do not close this ticket by setting the env var. MEASURED (probe G3b): with LIMBO_DISABLE_FILE_LOCK=1 the same copy SUCCEEDS against a live foreign holder, integrity_check ok, and it includes a row the holder wrote after we had already been refused once — so the cross-engine WAL read genuinely works and the lock is a guard, not an incompatibility. But that env var removes the guard PROCESS-WIDE and buys no shared locking protocol: turso locks the whole file with fcntl, C SQLite uses byte-range locks plus the -shm WAL index, and neither engine observes the other's. What was measured is one point-in-time copy, NOT correctness under sustained concurrent write pressure. Turning the guard off converts 'refuses to open' into 'may read torn state', which is the strictly worse failure.")
/// @yah:gotcha("THE FIX IS A PER-OPEN FLAG, NOT THE ENV VAR — READ THIS BEFORE ACCEPTING THIS TICKET'S FRAMING. This ticket's gotcha rejects LIMBO_DISABLE_FILE_LOCK=1 because it 'removes the guard PROCESS-WIDE', and that objection is correct about the env var and wrong about turso_core's capabilities: the lock is ALSO skipped per-handle. Read turso_core-0.7.2/io/unix.rs:67-72 in the registry — `if std::env::var(ENV_DISABLE_FILE_LOCK).is_err() && !flags.intersects(OpenFlags::ReadOnly | OpenFlags::NoLock) { unix_file.lock_file(true)? }`. So `OpenFlags::ReadOnly` (io/mod.rs:355) takes NO whole-file exclusive lock, scoped to that ONE file handle, with no env var and no effect on any other open in the process. The public seam is `turso_core::Database::open_file_with_flags(io, path, flags, opts, ...)` (lib.rs:701/814). io_uring.rs:463 and windows.rs:305 carry the identical condition, so this is not a unix-only accident. THE BACKUP PATH IS A READER AND SHOULD SAY SO. Both of turso-backup's source opens currently take the default write flags: snapshot.rs:281 `turso::Builder::new_local(db_path)` (the friendly wrapper, which is why the flag is not reachable from there) and stream.rs's CoreWalSeam::open. NOT MEASURED BY ME, and it is the first thing to measure: whether a ReadOnly open reproduces probe G3b's success (which was measured WITH the env var, i.e. the same no-lock effect) — extend oss/turso-backup/examples/foreign_checkpoint_probe.rs with a G3c that differs from G3b only in using the flag instead of the env var. NOTE ALSO, so nobody chases it: turso_core 0.7.2 has an experimental multiprocess-WAL mode (DatabaseOpts::enable_multiprocess_wal, MappedSharedWalCoordination, lib.rs:809-841) and it does NOT help here — it coordinates turso processes with each other via its own -wal coordination file, and C SQLite knows nothing about it.")
/// @yah:gotcha("THE FLAG ONLY ANSWERS HALF, AND THE OTHER HALF ALREADY HAS A MEASURED ANSWER IN THIS RELAY'S OWN PROBE. ReadOnly gets the file OPEN without stealing a lock; it buys no shared locking protocol, so this ticket's real objection survives — turso locks whole-file with fcntl, C SQLite uses byte-range locks plus the -shm WAL index, neither observes the other, and a checkpoint landing mid-copy can still hand back a torn image. IMPLEMENTING SQLite's ACTUAL READER PROTOCOL (registering a read-mark in the -shm index) IS NOT THE ANSWER: it means reimplementing the WAL-index locking protocol against a live foreign engine, which is a research project and a permanent compatibility liability. USE OPTIMISTIC VALIDATION INSTEAD, which needs no cooperation from C SQLite and which R858-F17's probe C ALREADY RAN by hand — its verdict line reads 'The source was verified unperturbed by the copy (identical WAL salt and max_frame before and after)'. Formalise that as the protocol rather than leaving it as a probe assertion: capture (WAL header salt1, salt2, mxFrame) plus the main file's size and change-counter BEFORE the copy, take the copy, re-read all of them AFTER, and accept only on an exact match; on any movement DISCARD and retry, bounded, then fail LOUDLY. That is textbook optimistic concurrency, it turns 'may read torn state' into 'detects torn state and refuses', and it is nearly free on the driving workload — headscale.db measured 94 KB. It also composes with R858-B19, which is adding the same WAL-header salt to the watermark; the parsing helper (`wal_hdr` in examples/foreign_checkpoint_probe.rs) is shared, so land B19 FIRST and reuse whatever it hoists rather than writing a second header parser. DO NOT close this ticket by setting the env var, and do not close it with ReadOnly alone — ReadOnly without the validation is exactly the 'refuses to open' -> 'may read torn state' trade this ticket names as strictly worse.")
/// @yah:handoff("FIXED AND MEASURED, BOTH HALVES, BOTH TIERS (@Ashguard:polaris, session:6ddd7379, 2026-09-10). The per-open flag is confirmed and the ticket's own objection to it is answered by optimistic validation, so this closes without the env var and without ReadOnly-alone. THE FLAG, MEASURED NOT ASSUMED: new probe G2r/G3c in examples/foreign_checkpoint_probe.rs differ from G2/G3b in exactly one variable each. Against a foreign sqlite3 3.51.0 holder open and idle, G2 (write flags) is still refused with 'Locking error: File is locked by another process' while G2r (CoreWalSeam::open_reader, OpenFlags::ReadOnly, NO env var) succeeds; G3c and G3b then agree EXACTLY -- both 8192 bytes, integrity_check ok, 4 rows including the row the holder wrote after we had already been refused once. So the flag reproduces G3b's success with no process-wide effect, and LIMBO_DISABLE_FILE_LOCK is never needed. NEW G6 closes the ticket's TITLE claim, which G2/G3 only approached: tail_frames through a ReadOnly seam with the foreign holder STILL attached returns 'Streamed seq 0 frames 1..=1' -- turso-backup can now tail a live foreign-written DB, not merely copy one.")
/// @yah:handoff("THE VALIDATION, AND ONE PLACE THE MEASUREMENT CONTRADICTED THE PLAN. Built on R858-B19's types as instructed, no second parser: WalSalt gained from_wal_file_header (bytes 16..24 of the 32-byte -wal header) beside the existing from_frame_header (bytes 8..16 of a frame header), both in one impl block, and a test asserts the two paths name the SAME salt on a live DB (wal_file_header_salt_matches_the_salt_read_through_the_seam) -- if they could disagree, validation would compare a salt the streamer never recorded. New WalFileHeader (page_size, checkpoint_seq, salt; read with no engine open) + SourceFingerprint {main_len, change_counter, wal, wal_len} + SourceFingerprint::read/stable_across, all in src/stream.rs. raw_consistent_copy_live now opens read-only and runs inside a new shared helper validated_against_source(db_path, what, take) which BOTH source tiers use. DEVIATION 1 (measured, deliberate): the ticket said capture mxFrame; stable_across EXCLUDES wal_len and the frame count, because a plain append cannot tear this algorithm (SQLite only appends within a generation and only a reset -- which re-rolls salt1 -- lets it overwrite an existing frame, so frames 1..=max_frame are immutable while the salt holds; a commit during our copy just means an earlier point in time). Including it buys no safety and costs everything: probe H5 measured the stricter rule refusing 10/12 copies in the HOT regime and 1/12 even in the CALM one, i.e. it would refuse backups of any database actually in use. A unit test pins both directions (fingerprint_ignores_an_append_and_catches_a_checkpoint). DEVIATION 2 (a real bug my first implementation had, found by probe H): the common shape of a caught race is NOT a clean torn image but 'short read on WAL frame at offset N' from wal_get_frame, a foreign checkpoint truncating the WAL mid-walk. My first cut propagated that with ?, so it aborted on attempt 1 and never used the retry budget. The fingerprint now CLASSIFIES the error: Err + source moved => retry (race symptom); Err + source held still => return the error as itself on attempt 1, since retrying cannot help (validation_surfaces_a_real_error_without_burning_the_budget pins that).")
/// @yah:handoff("PROBE H -- the concurrent-writer measurement, run in TWO regimes because one write rate can only prove half of it. HOT (4000-row body, writer autocheckpoint=16 pages, 40-row commits with no pause): 3 accepted / 9 refused-and-validated / 0 accepted-but-corrupt. CALM (the headscale shape: 200 rows, default autocheckpoint=1000, single-row commits every 15ms): 12 accepted / 0 refused / 0 corrupt. Every accepted image in both regimes passed PRAGMA integrity_check and was row-count-monotonic. So the protocol delivers a real backup WHILE a foreign process writes at a headscale-shaped rate, and reports a genuinely hot database as unbackupable-right-now rather than silently mis-copying it. Bound is COPY_VALIDATION_ATTEMPTS=4 with 0/20/40/60ms backoff, then a refusal naming both fingerprint samples verbatim. THE SECOND BLOCKED TIER IS ALSO FIXED (new probe S, which the ticket's gotcha named and probe G never touched). S1w vs S2 is the one-variable control: the same VACUUM INTO statement against the same live foreign-held source is REFUSED under write flags and SUCCEEDS under OpenFlags::ReadOnly (8192B, integrity ok, 50/50 rows). VACUUM INTO is NOT gated by DatabaseOpts::enable_vacuum -- only bare VACUUM is (turso_core-0.7.2/translate/vacuum.rs:39) -- so tier 1a keeps VACUUM INTO and its byte-deterministic gate-2 hash. snapshot.rs:vacuum_into now opens through turso_core with ReadOnly instead of turso::Builder (the friendly wrapper exposes no OpenFlags, which is why the flag was unreachable from there) and is wrapped in the same validated_against_source, removing its destination file at the start of each attempt since SQLite refuses an existing VACUUM INTO target. `use turso::Builder` moved into snapshot.rs's #[cfg(test)] module -- the library no longer opens a source through the friendly wrapper, only the test fixtures write through it.")
/// @yah:handoff("VERIFY, AND AN HONEST TEST-COUNT ATTRIBUTION. `cargo run --example foreign_checkpoint_probe -- d g` re-run BEFORE any edit to own the baseline: D0 control 3.46ms, D2 Blocked with 'database is locked (5)', G2/G3 REFUSED, G3b SUCCEEDED -- exactly the ticket's stated expectation. AFTER: D unchanged (D2 still blocked, D0 8.28ms -- the writable seam is still exclusive and SHOULD be, it is the restore direction); G2 still REFUSED, G2r/G3/G3c now SUCCEED, G3b unchanged, G6 Streamed. cargo clippy --all-targets clean. cargo test: 174 total, 0 failed, against the leader's 158/0 baseline -- and that delta is NOT all mine. +7 are mine and named (wal_file_header_salt_matches_the_salt_read_through_the_seam, wal_file_header_parse_needs_a_whole_header, fingerprint_ignores_an_append_and_catches_a_checkpoint, validation_accepts_a_quiescent_source, validation_refuses_when_the_source_moves_under_every_attempt, validation_surfaces_a_real_error_without_burning_the_budget, read_only_seam_reports_the_same_watermark_as_the_writable_one; all 7 verified green by name filter). The other +9 arrived mid-session from @Ashguard:eclipse (session:a3e5eed1, R850-F1) landing a new src/turso-backup/src/tail.rs in this crate; counted by grep, not claimed. SHARED-TREE NOTE: that same peer's tail.rs broke the whole crate's build for ~15 minutes (E0425 missing `use crate::stream::PreflightStage`, E0502 borrow conflict at tail.rs:390). I did NOT touch it -- I party.chat'd them the two fixes and waited; they cleared it and the final verification above ran on a green tree. Their src/dedup.rs snapshot_dedup_image doc already anticipates this ticket's API ('opens read-only and validates optimistically'), so the seam is compatible, but I warned them explicitly that raw_consistent_copy_live can now return Err under a hot writer and their appliance-tail caller must treat that as retry-later, not fatal.")
/// @yah:gotcha("TWO LIMITS OF THIS FIX A LATER READER MUST NOT OVERREAD. (1) OpenFlags::ReadOnly does NOT escape turso's process-global registry: Database::open_file_with_flags consults DATABASE_MANAGER keyed by file id BEFORE it looks at the flags (turso_core-0.7.2/lib.rs:940) and returns an already-open Database with the caller's flags DISCARDED. So inside one process that already holds a writable handle on the same file, open_reader silently gives you that writable handle -- the same trap snapshot.rs's upload_base_snapshot doc already records for roadcase. Cross-process (the headscale case, and every case this ticket is about) is unaffected. (2) The validation detects a fold that overlaps the copy; it does not prevent one, and it cannot make a sufficiently hot database backupable. Probe H's HOT regime refuses 9 of 12 copies by design. If a real workload lands there the answer is a different cadence or a bigger COPY_VALIDATION_ATTEMPTS, decided from measurement -- NOT loosening stable_across, which is the one thing standing between this and the torn image the ticket calls strictly worse.")
/// @yah:next("oss/yubaba/crates/tenant-streamer/src/main.rs:138 still opens its source seam with CoreWalSeam::open (writable, whole-file exclusive lock). It is OUT OF SCOPE for B18 (oss/turso-backup only) and was deliberately left alone, but it is now the only remaining source-side open in the fleet that locks out the application it is streaming. Switching it to CoreWalSeam::open_reader is a one-line change plus a decision about what the streamer should do when a tail is refused under write pressure -- yubaba's call, needs its own ticket.")
/// @yah:verify("cd oss/turso-backup && cargo run --example foreign_checkpoint_probe -- d g: expect D2 still blocked with 'database is locked (5)' (the writable seam is still exclusive, which is correct for restore), G2 still REFUSED, G2r/G3/G3c SUCCEEDED, G3b unchanged, G6 'Streamed seq 0 frames 1..=1'.")
/// @yah:verify("cd oss/turso-backup && cargo run --example foreign_checkpoint_probe -- h s: expect H VERDICT CORRECT (CALM regime 12/12 accepted, HOT regime mostly refused, 0 accepted-but-corrupt in both), and S1w REFUSED vs S2 SUCCEEDED as the one-variable flag control. Plus cargo test (174 passed / 0 failed, of which 7 are this ticket's) and cargo clippy --all-targets clean.")
/// @yah:verify("RE-RUN BY THE LEADER (@Ashguard:hydra, session:ee099a8e), independently, not from the courier's report. `cargo test` = 179 passed / 0 failed across seven targets (158 lib + 5 + 4 + 5 + 7 + 0 + 0). THAT IS +5 ON THE COURIER'S CLAIMED 174 AND THE COURIER IS NOT OVERCLAIMING — it is under-claiming: @Ashguard:eclipse (session:a3e5eed1, R850-F1) is landing tail.rs into this crate AND into oss/kamaji live, and the build-skew rail flagged three of their files changing during my own run. The attributable half checks out exactly: all SEVEN tests the courier named ran green by name filter (wal_file_header_salt_matches_the_salt_read_through_the_seam, wal_file_header_parse_needs_a_whole_header, fingerprint_ignores_an_append_and_catches_a_checkpoint, validation_accepts_a_quiescent_source, validation_refuses_when_the_source_moves_under_every_attempt, validation_surfaces_a_real_error_without_burning_the_budget, read_only_seam_reports_the_same_watermark_as_the_writable_one), 7 passed / 151 filtered out. PROBES, all re-run by me: `-- d g` gives G2 still REFUSED (write flags, 'File is locked by another process'), G2r SUCCEEDED, G3c and G3b agreeing exactly at 8192B / integrity ok / 4 rows, G6 'Streamed seq 0 frames 1..=1' through a ReadOnly seam with the holder still attached, and D2 still Blocked at 'database is locked (5)'. `-- h s` gives H VERDICT CORRECT with CALM 12/12 accepted and HOT 11 accepted / 1 refused / **0 accepted-but-corrupt** in both regimes — note my HOT split differs from the courier's 3/9 because the regime is timing-dependent; the zero-corrupt invariant is what matters and it held in both runs. S1w REFUSED vs S2 SUCCEEDED is the one-variable flag control on the snapshot tier.")
/// @yah:assumes("THE VALIDATION IS A FINGERPRINT, NOT A PROOF, and the residual hole is narrow but real — stated by the leader so a later reader does not mistake 'measured 0 corrupt in 24 rounds' for 'cannot tear'. `stable_across` (stream.rs:521) compares main_len, the main header's change_counter, and the 32-byte WAL header (page_size, checkpoint_seq, salt) — deliberately NOT wal_len, and DEVIATION 1's argument for that is sound. The uncovered shape is a PASSIVE foreign checkpoint that overwrites pages already present in the main file: it does not grow main_len, and it does not roll the WAL header (checkpoint_seq only moves on a WAL reset, not on a passive checkpoint). What is left holding the line there is change_counter — SQLite carries the counter in page 1, so a checkpointed transaction should move it. THAT IS THE UNVERIFIED STEP: probe H's own refusal message shows a window where main_len moved 1810432 -> 1863680 while change_counter stayed at 3, which means main and change_counter can move independently and I cannot conclude from this run that change_counter always moves when pages do. WHAT WOULD SETTLE IT: a probe that forces `PRAGMA wal_checkpoint(PASSIVE)` on a same-sized main file mid-copy and asserts the fingerprint catches it. Nothing here argues against shipping — this is strictly better than both the status quo (refuses to open) and the env var (may read torn state silently) — but do not cite it as an airtight guarantee, and do NOT loosen stable_across further without closing this first.")
pub fn start() {
    let _ = std::process::Command::new("systemctl")
        .args(["start", LITESTREAM_UNIT])
        .status();
}

/// Stop `litestream-headscale.service`.
pub fn stop() {
    let _ = std::process::Command::new("systemctl")
        .args(["stop", LITESTREAM_UNIT])
        .status();
}

/// Split `s3://bucket/path?endpoint=https://...` into
/// `(s3://bucket/path, Some("https://..."))`.
fn split_s3_url(url: &str) -> (String, Option<String>) {
    match url.split_once('?') {
        None => (url.to_owned(), None),
        Some((base, query)) => {
            let endpoint = query
                .split('&')
                .find_map(|kv| kv.strip_prefix("endpoint="))
                .map(|v| v.to_owned());
            (base.to_owned(), endpoint)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn split_url_no_query() {
        let (base, ep) = split_s3_url("s3://my-bucket/headscale");
        assert_eq!(base, "s3://my-bucket/headscale");
        assert!(ep.is_none());
    }

    #[test]
    fn split_url_with_endpoint() {
        let (base, ep) =
            split_s3_url("s3://my-bucket/headscale?endpoint=https://fsn1.your-objectstorage.com");
        assert_eq!(base, "s3://my-bucket/headscale");
        assert_eq!(ep.as_deref(), Some("https://fsn1.your-objectstorage.com"));
    }

    #[test]
    fn generate_config_contains_db_path() {
        let cfg = generate_config(
            &PathBuf::from("/etc/yah-cloud/headscale/headscale.db"),
            "s3://bucket/headscale",
        );
        assert!(
            cfg.contains("/etc/yah-cloud/headscale/headscale.db"),
            "db path missing"
        );
        assert!(cfg.contains("s3://bucket/headscale"), "s3 url missing");
        assert!(
            cfg.contains("LITESTREAM_ACCESS_KEY_ID"),
            "cred placeholder missing"
        );
    }

    /// R591-T3. `generate_config` used a `\` line-continuation, which strips
    /// the leading whitespace of the continued line — so `access-key-id` came
    /// out at column 0 instead of 8. The old test above passed anyway (it only
    /// asked whether the string appeared *somewhere*), and the config it
    /// described gave the replica no credentials at all.
    ///
    /// Every key under `- url:` is a sibling of it and must sit at the same
    /// indent as `endpoint`, with or without an endpoint present.
    #[test]
    fn every_replica_key_is_indented_under_its_url() {
        for url in [
            "s3://bucket/headscale",
            "s3://bucket/headscale?endpoint=https://fsn1.your-objectstorage.com",
        ] {
            let cfg = generate_config(&PathBuf::from("/var/lib/hs/headscale.db"), url);
            for key in ["access-key-id", "secret-access-key"] {
                let line = cfg
                    .lines()
                    .find(|l| l.trim_start().starts_with(key))
                    .unwrap_or_else(|| panic!("{key} missing from:\n{cfg}"));
                assert_eq!(
                    line.len() - line.trim_start().len(),
                    REPLICA_KEY_INDENT.len(),
                    "{key} must be a sibling of `- url:`, got {line:?} in:\n{cfg}"
                );
            }
        }
    }

    /// The `?endpoint=` query is litestream's `endpoint:` key, not part of the
    /// replica URL — a bucket URL carrying the query would be dialled verbatim.
    #[test]
    fn the_endpoint_query_becomes_a_key_and_leaves_the_url() {
        let cfg = generate_config(
            &PathBuf::from("/var/lib/hs/headscale.db"),
            "s3://bucket/headscale?endpoint=https://fsn1.your-objectstorage.com",
        );
        assert!(cfg.contains("- url: s3://bucket/headscale\n"), "{cfg}");
        assert!(
            cfg.contains("endpoint: https://fsn1.your-objectstorage.com"),
            "{cfg}"
        );
        assert!(
            !cfg.contains("?endpoint="),
            "query leaked into the url:\n{cfg}"
        );
    }

    /// The unit's own directives — `Restart=always`, no `[Install]`, no
    /// `headscale.service` binding, and the config path it shares with the
    /// replicate leg — moved to
    /// `app/yah/cli/tests/camp_systemd_unit_emit.rs::the_litestream_sidecar_unit_*`
    /// when the unit stopped being generated here (R858). It is shipped text
    /// now, so it is asserted where it is shipped from; generating a second
    /// copy in this crate purely to assert against would be asserting a copy
    /// that can drift from the file nodes actually run.
    ///
    /// What stays here is the half that is still generated: the config.
    /// [`install`] must write it somewhere `ProtectSystem=strict` permits, and
    /// that is the property this test holds.
    #[test]
    fn the_config_lives_where_a_hardened_yubaba_can_write_it() {
        // `yubaba.service` grants ReadWritePaths=/var/lib/yah/yubaba (plus
        // StateDirectory=yah/yubaba) and nothing under /etc. A config path
        // outside that grant is EROFS on every fleet node, and the caller
        // absorbs the error into a warn! — so the bug is silent.
        assert!(
            LITESTREAM_CONFIG_PATH.starts_with("/var/lib/yah/yubaba/"),
            "config must sit inside yubaba's writable state dir, got \
             {LITESTREAM_CONFIG_PATH}"
        );
    }

    /// `install` writes the config and nothing else. It used to also write a
    /// systemd unit, which it had no permission to do; a regression that
    /// reintroduces any `/etc` write reintroduces the silent EROFS.
    #[test]
    fn install_writes_the_config_and_only_the_config() {
        let tmp = std::env::temp_dir().join("yah-litestream-install-probe");
        let _ = std::fs::remove_dir_all(&tmp);
        std::fs::create_dir_all(&tmp).unwrap();
        let db = tmp.join("headscale.db");

        // Not calling `install` directly — it targets absolute host paths no
        // test may write. This asserts the payload it would write, which is
        // the part that carries meaning.
        let cfg = generate_config(&db, "s3://yah-headscale/headscale");
        assert!(cfg.contains("s3://yah-headscale/headscale"));
        assert!(
            !cfg.contains("[Service]") && !cfg.contains("ExecStart="),
            "the config is YAML, not a smuggled unit file:\n{cfg}"
        );
        let _ = std::fs::remove_dir_all(&tmp);
    }
}
