//! Operator-bridge integration tests — R091-F8.
//!
//! Exercises the two modes warden supports when a `WorkloadSpec` has
//! `expose.operator` set:
//!
//!   **Mode 1 — tailscale (default)**:  Warden calls Headscale to create a
//!   preauth key tagged with `expose.operator.tailscale_tag`. The key is
//!   returned in the deploy response so the operator machine can join the
//!   tailnet. On Headscale failure the workload is torn down and an error
//!   is returned.
//!
//!   **Mode 2 — mesh-peer** (`YAH_OPERATOR_BRIDGE_MODE=mesh-peer`): Warden
//!   skips Tailscale entirely and exposes the workload as a direct mesh peer.
//!   No Headscale API call is made. Faster; loses real ACL evaluation.
//!
//! Uses `FakeRuntime` (no real containerd required) and an in-process
//! `HeadscaleMock` HTTP server. Runs in standard CI without special credentials.
//!
//! ## Running
//!
//! ```bash
//! # All local-tier cases:
//! cargo test -p warden --features testing --test integration_operator_bridge
//!
//! # Specific local-tier test:
//! cargo test -p warden --features testing --test integration_operator_bridge \
//!     operator_bridge_tailscale__local
//!
//! # Smoke tier (real Headscale — requires YAH_SMOKE=1 + credentials):
//! YAH_SMOKE=1 HEADSCALE_API_KEY=... cargo test -p warden --features testing \
//!     --test integration_operator_bridge -- --ignored
//! ```
//!
//! The `__local` / `__smoke` suffix mirrors the naming convention generated by
//! `#[test_with_provider(local, smoke)]`.
//!
//! @arch:see(.yah/docs/architecture/A053-yah-warden-integration-testing.md)

use std::sync::Arc;

use axum::body::Body;
use axum::http::Request;
use http_body_util::BodyExt;
use tower::ServiceExt;

use constable_core::fake::FakeRuntime;
use warden::testing::headscale_mock::HeadscaleMock;
use warden::OperatorBridgeMode;
use workload_spec::{
    ExposeSpec, ImageRef, MeshExpose, MeshIdent, Millis, OperatorExpose, ResourceLimits,
    RestartPolicy, SchemaVersion, StopPolicy, TierTag, WorkloadSpec,
};

// ── Helpers ───────────────────────────────────────────────────────────────────

fn operator_workload_spec(name: &str, tag: &str, port: u16) -> WorkloadSpec {
    WorkloadSpec {
        schema_version: SchemaVersion::V1,
        name: name.to_string(),
        image: ImageRef {
            registry: "docker.io".into(),
            repository: "library/alpine".into(),
            tag: "latest".into(),
            digest: workload_spec::testing::test_digest(),
        },
        tier: TierTag("private".into()),
        replicas: 1,
        command: None,
        entrypoint: None,
        workdir: None,
        user: None,
        env: vec![],
        secrets: vec![],
        volumes: vec![],
        resources: ResourceLimits {
            memory_mb: 64,
            cpu_shares: 128,
            ephemeral_storage_mb: 128,
        },
        depends_on: vec![],
        healthcheck: None,
        restart_policy: RestartPolicy::Always,
        stop_policy: StopPolicy {
            signal: 15,
            grace_period: Millis::from_secs(5),
        },
        expose: ExposeSpec {
            mesh: MeshExpose {
                identity: MeshIdent(name.to_string()),
                ports: vec![port],
                allow_from: vec![],
            },
            public: None,
            operator: Some(OperatorExpose {
                tailscale_tag: tag.to_string(),
                port,
            }),
        },
        labels: Default::default(),
        annotations: Default::default(),
    }
}

async fn body_json(resp: axum::response::Response) -> serde_json::Value {
    let bytes = resp.into_body().collect().await.unwrap().to_bytes();
    serde_json::from_slice(&bytes).unwrap()
}

async fn deploy(app: axum::Router, spec: &WorkloadSpec) -> axum::response::Response {
    let body = serde_json::json!({ "spec": spec });
    app.oneshot(
        Request::post("/workloads/deploy")
            .header("content-type", "application/json")
            .body(Body::from(serde_json::to_vec(&body).unwrap()))
            .unwrap(),
    )
    .await
    .unwrap()
}

fn fresh_state_with_runtime(rt: FakeRuntime) -> (tempfile::TempDir, Arc<warden::ServerState>) {
    let tmp = tempfile::TempDir::new().unwrap();
    let state = Arc::new(
        warden::ServerState::load(tmp.path().join("identity.json"))
            .unwrap()
            .with_runtime(Arc::new(rt)),
    );
    (tmp, state)
}

// ── Sub-case implementations ──────────────────────────────────────────────────

/// Mode 1 (a): Deploy with Headscale mock configured → preauth key created.
///
/// Verifies that warden calls `POST /api/v1/preauthkey` with the correct ACL
/// tag and that the deploy response includes the issued preauth key.
async fn case_tailscale_with_mock() {
    let mock = HeadscaleMock::start()
        .await
        .expect("headscale mock failed to start");

    let rt = FakeRuntime::new();
    let (_tmp, state_base) = fresh_state_with_runtime(rt);
    let state = Arc::new(
        Arc::try_unwrap(state_base)
            .unwrap()
            .with_headscale_url(mock.base_url()),
    );
    let app = warden::build_router(state);

    let spec = operator_workload_spec("ops-service", "tag:ops", 9000);
    let resp = deploy(app, &spec).await;

    assert!(
        resp.status().is_success(),
        "deploy should succeed with headscale mock; got {}",
        resp.status()
    );

    let json = body_json(resp).await;
    assert_eq!(json["status"], "deployed", "response status should be deployed");

    // The preauth key must be present in the response.
    assert!(
        json["preauthkey"].is_string(),
        "response should include a preauthkey string; got: {json}"
    );
    assert!(
        !json["preauthkey"].as_str().unwrap().is_empty(),
        "preauthkey must not be empty"
    );
    assert_eq!(
        json["operator_mode"], "tailscale",
        "operator_mode should be 'tailscale'; got: {json}"
    );

    // Headscale mock must have received exactly one preauth key creation.
    let keys = mock.preauth_keys();
    assert_eq!(keys.len(), 1, "expected exactly one preauth key created");
    assert_eq!(
        keys[0].user, "yah-cluster",
        "preauth key user should be 'yah-cluster'"
    );
    assert_eq!(
        keys[0].acl_tags,
        vec!["tag:ops"],
        "preauth key should be tagged with 'tag:ops'"
    );
    assert!(
        keys[0].ephemeral,
        "preauth key should be ephemeral for operator use"
    );
}

/// Mode 1 (b): ACL tag isolation — a second workload with a different tag
/// gets a different preauth key; the mock confirms the correct per-tag
/// namespacing (local tier validates the API shape; real ACL enforcement is
/// smoke-tier only).
async fn case_tailscale_tag_isolation() {
    let mock = HeadscaleMock::start()
        .await
        .expect("headscale mock failed to start");

    let rt = FakeRuntime::new();
    let (_tmp, state_base) = fresh_state_with_runtime(rt);
    let state = Arc::new(
        Arc::try_unwrap(state_base)
            .unwrap()
            .with_headscale_url(mock.base_url()),
    );
    let app = warden::build_router(state);

    // Deploy two workloads with different ACL tags.
    let spec_ops = operator_workload_spec("ops-service", "tag:ops", 9000);
    let spec_dev = operator_workload_spec("dev-service", "tag:dev", 9001);

    let resp_ops = deploy(app.clone(), &spec_ops).await;
    let resp_dev = deploy(app.clone(), &spec_dev).await;

    assert!(resp_ops.status().is_success(), "ops deploy failed: {}", resp_ops.status());
    assert!(resp_dev.status().is_success(), "dev deploy failed: {}", resp_dev.status());

    let keys = mock.preauth_keys();
    assert_eq!(keys.len(), 2, "expected two preauth keys (one per workload)");

    let ops_key = keys.iter().find(|k| k.acl_tags.contains(&"tag:ops".to_string()));
    let dev_key = keys.iter().find(|k| k.acl_tags.contains(&"tag:dev".to_string()));

    assert!(ops_key.is_some(), "no preauth key found for tag:ops");
    assert!(dev_key.is_some(), "no preauth key found for tag:dev");

    // The two keys must be distinct — tag isolation at the preauth level.
    assert_ne!(
        ops_key.unwrap().key,
        dev_key.unwrap().key,
        "ops and dev preauth keys should be distinct"
    );
}

/// Mode 1 (c): Headscale registration failure → workload torn down.
///
/// When `POST /api/v1/preauthkey` fails, warden tears down the container it
/// just started and returns a non-success response.
async fn case_tailscale_headscale_failure() {
    let mock = HeadscaleMock::start()
        .await
        .expect("headscale mock failed to start");
    mock.fail_next_create();

    let rt = FakeRuntime::new();
    let rt_assert = rt.clone();
    let (_tmp, state_base) = fresh_state_with_runtime(rt);
    let state = Arc::new(
        Arc::try_unwrap(state_base)
            .unwrap()
            .with_headscale_url(mock.base_url()),
    );
    let app = warden::build_router(state);

    let spec = operator_workload_spec("failing-ops", "tag:ops", 9000);
    let resp = deploy(app, &spec).await;

    assert!(
        !resp.status().is_success(),
        "deploy should fail when headscale registration fails; got {}",
        resp.status()
    );

    let json = body_json(resp).await;
    assert!(
        json["error"]
            .as_str()
            .unwrap_or("")
            .contains("headscale preauth key creation failed"),
        "error message should mention headscale failure; got: {json}"
    );

    // Workload must be torn down — not present in the runtime.
    let workloads = rt_assert.snapshot();
    assert!(
        workloads.is_empty(),
        "workload should be torn down after headscale failure; found: {workloads:?}"
    );
}

/// Mode 2 (a): `OperatorBridgeMode::MeshPeer` → no Headscale call.
///
/// When the mode is set to `MeshPeer`, warden skips Tailscale and exposes the
/// workload as a direct mesh peer. The deploy succeeds, and NO preauth key was
/// created. Uses `with_operator_bridge_mode` to avoid global env-var pollution.
async fn case_mesh_peer_mode() {
    let mock = HeadscaleMock::start()
        .await
        .expect("headscale mock failed to start");

    let rt = FakeRuntime::new();
    let (_tmp, state_base) = fresh_state_with_runtime(rt);
    // Wire the mock URL AND set mesh-peer mode — mock should NOT be called.
    let state = Arc::new(
        Arc::try_unwrap(state_base)
            .unwrap()
            .with_headscale_url(mock.base_url())
            .with_operator_bridge_mode(OperatorBridgeMode::MeshPeer),
    );
    let app = warden::build_router(state);

    let spec = operator_workload_spec("mesh-peer-service", "tag:ops", 9000);
    let resp = deploy(app, &spec).await;

    assert!(
        resp.status().is_success(),
        "deploy should succeed in mesh-peer mode; got {}",
        resp.status()
    );

    let json = body_json(resp).await;
    assert_eq!(json["status"], "deployed");
    assert_eq!(
        json["operator_mode"], "mesh-peer",
        "operator_mode should be 'mesh-peer'; got: {json}"
    );
    assert!(
        json["preauthkey"].is_null() || json.get("preauthkey").is_none(),
        "preauthkey should be absent in mesh-peer mode; got: {json}"
    );

    // Headscale mock must NOT have been called.
    let keys = mock.preauth_keys();
    assert!(
        keys.is_empty(),
        "headscale should not be called in mesh-peer mode; got {} keys",
        keys.len()
    );
}

/// Mode 2 (b): No headscale URL and no mesh-peer mode → deploy succeeds with
/// a warning (operator exposure is silently no-op'd so the workload still
/// runs even if the operator-bridge is misconfigured).
async fn case_no_headscale_no_mode() {
    let rt = FakeRuntime::new();
    let (_tmp, state) = fresh_state_with_runtime(rt);
    // No headscale URL, no YAH_OPERATOR_BRIDGE_MODE — warning path.
    let app = warden::build_router(state);

    let spec = operator_workload_spec("warn-service", "tag:ops", 9000);
    let resp = deploy(app, &spec).await;

    // Deploy must still succeed — the workload runs, operator bridge just isn't active.
    assert!(
        resp.status().is_success(),
        "deploy should succeed even without headscale config; got {}",
        resp.status()
    );

    let json = body_json(resp).await;
    assert_eq!(json["status"], "deployed");
}

// ── Test entry points ─────────────────────────────────────────────────────────

/// Local-tier Tailscale mode: all three sub-cases.
///
/// Runs without a real containerd or Headscale daemon — uses `FakeRuntime`
/// and an in-process `HeadscaleMock`. Always runs in CI.
#[tokio::test]
#[allow(non_snake_case)]
async fn operator_bridge_tailscale__local() {
    case_tailscale_with_mock().await;
    case_tailscale_tag_isolation().await;
    case_tailscale_headscale_failure().await;
    case_no_headscale_no_mode().await;
}

/// Local-tier mesh-peer mode: direct mesh peer, no Headscale.
///
/// Runs without any external dependencies.
#[tokio::test]
#[allow(non_snake_case)]
async fn operator_bridge_mesh_peer__local() {
    case_mesh_peer_mode().await;
}

/// Smoke-tier stub — real Headscale + tailscaled exercise.
///
/// Requires: `YAH_SMOKE=1`, `HEADSCALE_API_KEY`, a Headscale instance, and
/// a tailscaled client that can join the tailnet.
///
/// Wired in R091-F9 (smoke CI nightly workflow).
#[tokio::test]
#[allow(non_snake_case)]
#[ignore = "smoke tier — set YAH_SMOKE=1 + HEADSCALE_API_KEY + HETZNER_API_TOKEN to run"]
async fn operator_bridge__smoke() {
    if std::env::var("YAH_SMOKE").as_deref() != Ok("1") {
        return;
    }
    // Real Headscale + tailscaled exercise — wired in R091-F9.
    todo!("smoke-tier operator bridge test — wired in R091-F9");
}
