//! R330-F40 guard (b), pointed at what the producers ACTUALLY emit.
//!
//! The unit tests in `feed.rs` and `r2.rs` run `untyped_hash_fields` over
//! hand-written fixtures, which proves the function works but not that the
//! release pipeline obeys it — the three publish legs build their JSON in bash
//! and `jq` and never pass through this crate. That gap is the whole reason
//! this file exists.
//!
//! The fixtures under `tests/fixtures/producer/` are not hand-written. They are
//! the output of executing the real step bodies out of
//! `.github/workflows/release.yml` and the real heredoc out of
//! `scripts/publish-desktop.sh`, generated by `scripts/check-producer-fixtures.sh`
//! in the yah monorepo. That script also DIFFS them on every run, so a producer
//! whose manifest shape changes fails there and the new bytes then have to pass
//! the assertions here.
//!
//! WHY THE FIXTURES ARE COMMITTED RATHER THAN GENERATED AT TEST TIME: this crate
//! is exported standalone (`oss/yubaba` is its own workspace, mirrored to
//! github.com/yah-ai/yubaba), so a test here cannot reach up into the
//! monorepo's `.github/`. Committed bytes are what make the check work on both
//! sides of the export boundary.

use yah_almanac::{
    feed_from_channel_manifest, feed_from_index_manifest, feed_from_triples_manifest,
    untyped_hash_fields,
};

fn fixture(name: &str) -> String {
    let path = format!("{}/tests/fixtures/producer/{name}", env!("CARGO_MANIFEST_DIR"));
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("missing producer fixture {path}: {e}\n\
             regenerate with scripts/check-producer-fixtures.sh --write"))
}

fn json(name: &str) -> serde_json::Value {
    serde_json::from_str(&fixture(name))
        .unwrap_or_else(|e| panic!("producer fixture {name} is not valid JSON: {e}"))
}

const ALL: &[&str] = &[
    "cli-latest.json",
    "cli-index.json",
    "mesofact-fragment.json",
    "yubaba-fragment.json",
    "desktop-release-manifest.json",
];

#[test]
fn no_producer_emits_an_untyped_digest() {
    // THE guard, against real bytes. A publish leg that grows a raw-hex field
    // fails here, and the failure names the exact path.
    for name in ALL {
        let found = untyped_hash_fields(&json(name));
        assert!(
            found.is_empty(),
            "{name} carries untagged digest(s) at {found:?} — tag them `blake3:<hex>` \
             / `sha256:<hex>`, or grandfather the exact path in LEGACY_BARE_HEX_PATHS \
             with a written reason"
        );
    }
}

#[test]
fn every_producer_publishes_a_blake3_identity() {
    // Policy (1): blake3 is THE asset hash, and every leg emits one.
    for name in ALL {
        let doc = json(name);
        let hash = find_hash(&doc)
            .unwrap_or_else(|| panic!("{name} publishes no `hash` field at all"));
        assert!(
            hash.starts_with("blake3:"),
            "{name} publishes `hash` = {hash:?}; blake3 is the canonical identity"
        );
    }
}

#[test]
fn every_producer_publishes_a_tagged_sha256_bootstrap_aid() {
    for name in ALL {
        let doc = json(name);
        let boot = find_key(&doc, "bootstrap_hash")
            .unwrap_or_else(|| panic!("{name} publishes no `bootstrap_hash`"));
        assert!(
            boot.starts_with("sha256:"),
            "{name} publishes `bootstrap_hash` = {boot:?}; the curl|sh aid is always sha256"
        );
    }
}

#[test]
fn the_install_pointer_keeps_its_bare_sha256_for_installers_in_the_wild() {
    // Back-compat is the non-negotiable constraint: every copy of install.sh
    // already running reads `.triples[$t].sha256`. If this assertion ever
    // fails, published installs break — do not "fix" it by deleting the test.
    let doc = json("cli-latest.json");
    let bare = doc["triples"]["aarch64-apple-darwin"]["sha256"]
        .as_str()
        .expect("cli latest.json must keep the bare sha256 key");
    assert_eq!(bare.len(), 64, "the legacy key must stay a bare digest, not become tagged");
    let boot = doc["triples"]["aarch64-apple-darwin"]["bootstrap_hash"].as_str().unwrap();
    assert_eq!(
        boot,
        format!("sha256:{bare}"),
        "the tagged aid and the legacy bare key must be the same digest"
    );
}

#[test]
fn the_install_pointer_maps_onto_a_feed_with_a_blake3_identity() {
    let feed = feed_from_triples_manifest(&fixture("cli-latest.json"))
        .expect("the real cli producer output must parse as the install-pointer shape");
    let asset = &feed.releases[0].assets[0];
    assert_eq!(asset.hash.as_ref().unwrap().algo().tag(), "blake3");
    assert_eq!(asset.bootstrap_hash.as_ref().unwrap().algo().tag(), "sha256");
    // …and the derived feed is itself clean.
    let value = serde_json::to_value(&feed).unwrap();
    assert!(untyped_hash_fields(&value).is_empty());
}

#[test]
fn the_desktop_manifest_maps_onto_a_feed_with_a_blake3_identity() {
    let feed = feed_from_channel_manifest(&fixture("desktop-release-manifest.json"))
        .expect("the real desktop producer output must parse as the channel shape");
    let asset = &feed.releases[0].assets[0];
    assert_eq!(asset.platform, "macos-arm64");
    assert_eq!(asset.hash.as_ref().unwrap().algo().tag(), "blake3");
    assert_eq!(asset.bootstrap_hash.as_ref().unwrap().algo().tag(), "sha256");
    let value = serde_json::to_value(&feed).unwrap();
    assert!(untyped_hash_fields(&value).is_empty());
}

#[test]
fn the_guard_actually_bites_on_a_real_producer_shape() {
    // A guard nobody has watched fail is not known to guard anything. Inject
    // the realistic drift — a new field carrying raw hex, and a REUSE of a
    // legacy key name at a path that is not the grandfathered one — into the
    // genuine producer output, and confirm both are caught.
    let mut doc = json("cli-latest.json");
    let hex = "e".repeat(64);
    doc["triples"]["aarch64-apple-darwin"]["digest"] = serde_json::json!(hex);
    let found = untyped_hash_fields(&doc);
    assert_eq!(found, vec!["$.triples.aarch64-apple-darwin.digest"]);

    let mut doc = json("cli-latest.json");
    doc["triples"]["aarch64-apple-darwin"]["attestation"] = serde_json::json!({ "sha256": hex });
    let found = untyped_hash_fields(&doc);
    assert_eq!(
        found,
        vec!["$.triples.aarch64-apple-darwin.attestation.sha256"],
        "a legacy key NAME at a new path must not be waved through"
    );
}

// ── The accumulating version index (R330-F38) ───────────────────────────────

#[test]
fn the_index_carries_no_bare_digest_at_all() {
    // STRONGER than `untyped_hash_fields`, and deliberately so. That function
    // asks "is any bare hex here un-grandfathered"; this asks "is a legacy key
    // present AT ALL". The index is a PERMANENT accumulating record with no
    // in-the-wild consumer, so the answer has to be no from its first byte —
    // there is nothing to grandfather and never will be. If this fails, the
    // fix is the `del(.sha256, .blake3)` in the producer, NOT a new entry in
    // LEGACY_BARE_HEX_PATHS: that list exists to grandfather ALREADY-PUBLISHED
    // keys and is meant to shrink, so adding a brand-new surface to it inverts
    // its whole purpose.
    let doc = json("cli-index.json");
    for version in doc["versions"].as_array().expect("the index is a version list") {
        for (triple, entry) in version["triples"].as_object().expect("per-triple map") {
            for legacy in ["sha256", "blake3"] {
                assert!(
                    entry.get(legacy).is_none(),
                    "{triple} in index version {} carries a bare `{legacy}` — strip it in \
                     the producer's del(), do not widen LEGACY_BARE_HEX_PATHS",
                    version["version"],
                );
            }
            assert!(
                entry["hash"].as_str().is_some_and(|h| h.starts_with("blake3:")),
                "{triple} must keep a tagged blake3 identity"
            );
            assert!(
                entry["bootstrap_hash"].as_str().is_some_and(|h| h.starts_with("sha256:")),
                "{triple} must keep a tagged sha256 bootstrap aid"
            );
        }
    }
}

#[test]
fn the_index_maps_onto_a_multi_version_feed_with_per_version_links() {
    // The feature: /releases lists every published version with links that
    // resolve to THAT version's bytes.
    let feed = feed_from_index_manifest(&fixture("cli-index.json"))
        .expect("the real index producer output must parse as the index shape");
    assert!(!feed.releases.is_empty());
    for release in &feed.releases {
        assert!(!release.assets.is_empty(), "{} lists no downloads", release.version);
        for asset in &release.assets {
            assert_eq!(asset.hash.as_ref().unwrap().algo().tag(), "blake3");
            assert_eq!(asset.bootstrap_hash.as_ref().unwrap().algo().tag(), "sha256");
            assert!(
                asset.url.contains(&format!("/yah/{}/", release.version)),
                "{} links to {}, which is another version's bytes",
                release.version,
                asset.url
            );
        }
    }
    let value = serde_json::to_value(&feed).unwrap();
    assert!(untyped_hash_fields(&value).is_empty());
}

#[test]
fn the_guard_bites_on_a_bare_digest_in_the_index() {
    // The anti-widening property, demonstrated failing rather than asserted.
    // `$.triples.*.sha256` grandfathers a bare digest in the install POINTER;
    // the same key one level deeper — inside the index — must still be caught,
    // or the index could silently accumulate untyped hex forever.
    let mut doc = json("cli-index.json");
    let hex = "e".repeat(64);
    doc["versions"][0]["triples"]["aarch64-apple-darwin"]["sha256"] = serde_json::json!(hex);
    assert_eq!(
        untyped_hash_fields(&doc),
        vec!["$.versions[0].triples.aarch64-apple-darwin.sha256"],
        "a bare digest inside the index must be flagged, not waved through by the \
         pointer's grandfathered path"
    );
}

/// The canonical `hash` field, wherever this producer's shape puts it.
fn find_hash(doc: &serde_json::Value) -> Option<String> {
    find_key(doc, "hash")
}

fn find_key(doc: &serde_json::Value, key: &str) -> Option<String> {
    match doc {
        serde_json::Value::Object(map) => {
            if let Some(serde_json::Value::String(s)) = map.get(key) {
                return Some(s.clone());
            }
            map.values().find_map(|v| find_key(v, key))
        }
        serde_json::Value::Array(items) => items.iter().find_map(|v| find_key(v, key)),
        _ => None,
    }
}
