//! Public-ingress integration tests — R091-F7.
//!
//! Exercises the three paths yubaba takes when a `WorkloadSpec` has
//! `expose.public` set:
//!
//!   (a) `cloudflared-mock` configured → tunnel route registered on deploy.
//!   (b) No cloudflared URL configured → port-mapping fallback, deploy succeeds.
//!   (c) Tunnel registration fails → container torn down, deploy returns error.
//!
//! Uses `FakeRuntime` (no real containerd required) and an in-process
//! `CloudflaredMock` HTTP server. Runs in standard CI without special credentials.
//!
//! ## Running
//!
//! ```bash
//! # All local-tier cases (all three sub-cases inside one function):
//! cargo test -p yubaba --features testing --test integration_public_ingress public_ingress__local
//!
//! # Smoke tier (real Cloudflare tunnel — requires YAH_SMOKE=1 + CF credentials):
//! YAH_SMOKE=1 CLOUDFLARE_TOKEN=... cargo test -p yubaba --features testing \
//!     --test integration_public_ingress -- --ignored
//! ```
//!
//! The `__local` / `__smoke` suffix mirrors the naming convention generated by
//! `#[test_with_provider(local, smoke)]` so the same cargo filter patterns work
//! across all integration test files. These tests don't need the provider macro
//! because they use `FakeRuntime` directly and never require a container socket.
//!
//! @arch:see(.yah/docs/architecture/A053-yah-yubaba-integration-testing.md)

use std::sync::Arc;

use axum::body::Body;
use axum::http::Request;
use http_body_util::BodyExt;
use tower::ServiceExt;

use kamaji::fake::FakeRuntime;
use workload_spec::{
    ExposeSpec, ImageRef, MeshExpose, MeshIdent, Millis, PublicExpose, PublicTls, ResourceLimits,
    RestartPolicy, SchemaVersion, StopPolicy, TierTag, WorkloadSpec,
};
use yubaba::testing::cloudflared_mock::CloudflaredMock;

// ── Helpers ───────────────────────────────────────────────────────────────────

fn public_workload_spec(name: &str, hostname: &str, port: u16) -> WorkloadSpec {
    WorkloadSpec {
        schema_version: SchemaVersion::V1,
        name: name.to_string(),
        image: ImageRef {
            registry: "docker.io".into(),
            repository: "library/alpine".into(),
            tag: "latest".into(),
            digest: workload_spec::testing::test_digest(),
        },
        // Shape validation requires expose.public.port to be in expose.mesh.ports.
        tier: TierTag("public".into()),
        tenant: workload_spec::TenantId::singleton(),
        namespace: workload_spec::NamespaceId::singleton(),
        replicas: 1,
        command: None,
        entrypoint: None,
        workdir: None,
        user: None,
        env: vec![],
        secrets: vec![],
        volumes: vec![],
        resources: ResourceLimits {
            memory_mb: 64,
            cpu_millis: 128,
            ephemeral_storage_mb: 128,
        },
        depends_on: vec![],
        healthcheck: None,
        restart_policy: RestartPolicy::Always,
        archetype: None,
        stop_policy: StopPolicy {
            signal: 15,
            grace_period: Millis::from_secs(5),
        },
        expose: ExposeSpec {
            mesh: MeshExpose {
                identity: MeshIdent(name.to_string()),
                ports: vec![port],
                allow_from: vec![],
            },
            public: Some(PublicExpose {
                hostname: hostname.to_string(),
                port,
                tls: PublicTls::CfManaged,
            }),
            operator: None,
        },
        labels: Default::default(),
        annotations: Default::default(),
    }
}

async fn body_json(resp: axum::response::Response) -> serde_json::Value {
    let bytes = resp.into_body().collect().await.unwrap().to_bytes();
    serde_json::from_slice(&bytes).unwrap()
}

async fn deploy(app: axum::Router, spec: &WorkloadSpec) -> axum::response::Response {
    let body = serde_json::json!({ "spec": spec });
    app.oneshot(
        Request::post("/workloads/deploy")
            .header("content-type", "application/json")
            .body(Body::from(serde_json::to_vec(&body).unwrap()))
            .unwrap(),
    )
    .await
    .unwrap()
}

// ── Sub-case implementations ──────────────────────────────────────────────────
//
// These are plain async functions (not #[tokio::test]) called from the combined
// `public_ingress__local` and `public_ingress__smoke` test functions below.

/// (a) Deploy with mock → tunnel route registered.
///
/// Verifies the mock receives exactly one registration with the correct hostname
/// and service URL.
async fn case_with_mock() {
    let mock = CloudflaredMock::start()
        .await
        .expect("cloudflared mock failed to start");

    let rt = FakeRuntime::new();
    let tmp = tempfile::TempDir::new().unwrap();
    let state = Arc::new(
        yubaba::ServerState::load(tmp.path().join("identity.json"))
            .unwrap()
            .with_runtime(Arc::new(rt))
            .with_cloudflared_url(mock.base_url()),
    );
    let app = yubaba::build_router(state);

    let spec = public_workload_spec("test-api", "api.example.com", 8080);
    let resp = deploy(app, &spec).await;

    assert!(
        resp.status().is_success(),
        "deploy should succeed with mock; got {}",
        resp.status()
    );

    let registrations = mock.registrations();
    assert_eq!(registrations.len(), 1, "expected one tunnel registration");
    assert_eq!(
        registrations[0].hostname, "api.example.com",
        "tunnel hostname mismatch"
    );
    assert!(
        registrations[0].service_url.contains(":8080"),
        "service_url should include port 8080; got: {}",
        registrations[0].service_url
    );
}

/// (b) Deploy without cloudflared URL → port-mapping fallback.
///
/// When no `cloudflared_url` is set, yubaba logs a warning and falls back to
/// docker-style port mapping. The deploy still succeeds.
async fn case_port_mapping_fallback() {
    let rt = FakeRuntime::new();
    let tmp = tempfile::TempDir::new().unwrap();
    // No cloudflared URL — port-mapping fallback path.
    let state = Arc::new(
        yubaba::ServerState::load(tmp.path().join("identity.json"))
            .unwrap()
            .with_runtime(Arc::new(rt)),
    );
    let app = yubaba::build_router(state);

    let spec = public_workload_spec("fallback-api", "api.example.com", 9090);
    let resp = deploy(app, &spec).await;

    assert!(
        resp.status().is_success(),
        "deploy should succeed with port-mapping fallback; got {}",
        resp.status()
    );

    let json = body_json(resp).await;
    assert_eq!(
        json["ident"], "fallback-api",
        "response ident should match the workload name"
    );
}

/// (c) Tunnel registration failure → workload torn down.
///
/// When tunnel registration fails (mock returns 500), yubaba tears down the
/// container it just started and returns a non-success response. The workload
/// must be absent from the runtime after the failed deploy.
async fn case_tunnel_failure() {
    let mock = CloudflaredMock::start()
        .await
        .expect("cloudflared mock failed to start");
    // Arm the mock to fail the next registration POST.
    mock.fail_next_registration();

    let rt = FakeRuntime::new();
    // Retain a second handle to the same inner state for post-deploy assertions.
    let rt_assert = rt.clone();

    let tmp = tempfile::TempDir::new().unwrap();
    let state = Arc::new(
        yubaba::ServerState::load(tmp.path().join("identity.json"))
            .unwrap()
            .with_runtime(Arc::new(rt))
            .with_cloudflared_url(mock.base_url()),
    );
    let app = yubaba::build_router(state);

    let spec = public_workload_spec("failing-api", "api.example.com", 8080);
    let resp = deploy(app, &spec).await;

    // Deploy must fail when tunnel registration fails.
    assert!(
        !resp.status().is_success(),
        "deploy should fail when tunnel registration fails; got {}",
        resp.status()
    );

    let json = body_json(resp).await;
    assert!(
        json["error"]
            .as_str()
            .unwrap_or("")
            .contains("tunnel registration failed"),
        "error message should mention tunnel registration failure; got: {}",
        json
    );

    // Workload must be torn down — not present in the runtime.
    let workloads = rt_assert.snapshot();
    assert!(
        workloads.is_empty(),
        "workload should be torn down after tunnel registration failure; found: {:?}",
        workloads
    );
}

// ── Test entry points ─────────────────────────────────────────────────────────

/// Local-tier combined test: all three public-ingress sub-cases.
///
/// Runs without a real containerd or cloudflared daemon — uses `FakeRuntime`
/// and an in-process `CloudflaredMock`. Always runs in CI.
#[tokio::test]
#[allow(non_snake_case)]
async fn public_ingress__local() {
    case_with_mock().await;
    case_port_mapping_fallback().await;
    case_tunnel_failure().await;
}

/// Smoke-tier stub — real Cloudflare Tunnel exercise.
///
/// Requires: `YAH_SMOKE=1`, `CLOUDFLARE_TOKEN`, a provisioned Hetzner machine
/// running yubaba, and a CF zone configured for the test hostname.
///
/// Wired in R091-F9 (smoke CI nightly workflow).
#[tokio::test]
#[allow(non_snake_case)]
#[ignore = "smoke tier — set YAH_SMOKE=1 + CLOUDFLARE_TOKEN + HETZNER_API_TOKEN to run"]
async fn public_ingress__smoke() {
    if std::env::var("YAH_SMOKE").as_deref() != Ok("1") {
        return;
    }
    // Real CF tunnel exercise — wired in R091-F9 smoke CI.
    todo!("smoke-tier public ingress test — wired in R091-F9");
}
